import { useParams, Link, useLocation } from "wouter";
import {
  useGetFinding,
  useUpdateFinding,
  useCreateRemediation
} from "@workspace/api-client-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  ShieldAlert,
  Target,
  AlertTriangle,
  CheckCircle2,
  XCircle,
  HelpCircle,
  Wrench,
  Info,
  Github,
  Loader2,
  Zap,
  Code2,
  ExternalLink,
  ArrowLeft,
  RefreshCw,
} from "lucide-react";
import { format } from "date-fns";
import { useState } from "react";
import { getSlaStatus } from "@/lib/sla";

function SeverityBadge({ severity }: { severity: string }) {
  const colors: Record<string, string> = {
    critical: "bg-[hsl(var(--critical))] text-white",
    high: "bg-[hsl(var(--high))] text-white",
    medium: "bg-[hsl(var(--medium))] text-black",
    low: "bg-[hsl(var(--low))] text-black",
    info: "bg-[hsl(var(--info))] text-white",
  };
  return (
    <Badge className={`${colors[severity.toLowerCase()] ?? "bg-slate-500 text-white"} border-none uppercase text-xs px-2 py-1`}>
      {severity}
    </Badge>
  );
}

function AiStreamPanel({
  endpoint, buttonLabel, icon, title, description, emptyText,
}: {
  endpoint: string; buttonLabel: string; icon: React.ReactNode;
  title: string; description: string; emptyText: string;
}) {
  const [text, setText] = useState("");
  const [loading, setLoading] = useState(false);
  const [done, setDone] = useState(false);

  async function generate() {
    setText(""); setDone(false); setLoading(true);
    try {
      const res = await fetch(endpoint, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({}) });
      if (!res.ok) throw new Error("Request failed");
      const reader = res.body!.getReader();
      const decoder = new TextDecoder();
      let buf = "";
      while (true) {
        const { done: dr, value } = await reader.read();
        if (dr) break;
        buf += decoder.decode(value, { stream: true });
        const lines = buf.split("\n");
        buf = lines.pop() ?? "";
        for (const line of lines) {
          if (!line.startsWith("data: ")) continue;
          try {
            const d = JSON.parse(line.slice(6));
            if (d.content) setText(p => p + d.content);
            if (d.done) setDone(true);
          } catch { /* ignore */ }
        }
      }
    } catch { setText("Failed to generate AI content. Please try again."); }
    finally { setLoading(false); }
  }

  return (
    <Card className="border-violet-500/20">
      <CardHeader className="flex flex-row items-center justify-between pb-3">
        <div>
          <CardTitle className="text-base">{title}</CardTitle>
          <CardDescription>{description}</CardDescription>
        </div>
        <Button size="sm" onClick={generate} disabled={loading}
          className="bg-violet-600 hover:bg-violet-700 text-white flex-shrink-0 gap-2">
          {loading ? <><Loader2 className="w-4 h-4 animate-spin" />Generating…</> : <>{icon}{buttonLabel}</>}
        </Button>
      </CardHeader>
      <CardContent>
        {!text && !loading && (
          <p className="text-sm text-muted-foreground text-center py-6">{emptyText}</p>
        )}
        {(text || loading) && (
          <div className="prose prose-sm dark:prose-invert max-w-none leading-relaxed">
            {text.split(/(```[\s\S]*?```)/g).map((part, i) => {
              if (part.startsWith("```")) {
                const code = part.slice(3).replace(/^[^\n]*\n/, "").slice(0, -3);
                return <pre key={i} className="bg-black/40 border border-border rounded-lg p-4 overflow-x-auto text-xs font-mono my-3"><code>{code}</code></pre>;
              }
              return <span key={i}>{part.split("\n").map((line, j, arr) => (
                <span key={j}>{line}{j < arr.length - 1 && <br />}</span>
              ))}</span>;
            })}
            {loading && <span className="inline-block w-2 h-4 bg-violet-400 animate-pulse ml-1 align-middle" />}
          </div>
        )}
        {done && <p className="text-xs text-muted-foreground mt-4 pt-3 border-t border-border">Generated by Claude Sonnet · Replit AI Integrations</p>}
      </CardContent>
    </Card>
  );
}

export default function FindingDetail() {
  const params = useParams();
  const [, setLocation] = useLocation();
  const findingId = params.id as string;
  const [ghLoading, setGhLoading] = useState(false);
  const [ghIssueUrl, setGhIssueUrl] = useState<string | null>(null);
  const [ghError, setGhError] = useState<string | null>(null);

  async function createGithubIssue() {
    setGhLoading(true); setGhError(null);
    try {
      const r = await fetch("/api/integrations/github/create-issue", {
        method: "POST", credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ finding_id: findingId }),
      });
      const d = await r.json();
      if (!r.ok) throw new Error(d.error ?? "Failed");
      setGhIssueUrl(d.issue_url);
    } catch (err: unknown) {
      setGhError(err instanceof Error ? err.message : "Failed to create issue");
    } finally { setGhLoading(false); }
  }

  const { data: finding, isLoading } = useGetFinding(findingId, {
    query: { enabled: !!findingId }
  });

  const updateFinding = useUpdateFinding({});

  const createRemediation = useCreateRemediation({
    mutation: {
      onSuccess: () => { setLocation("/remediations"); }
    }
  });

  if (isLoading) {
    return <div className="p-8 flex justify-center text-muted-foreground"><Loader2 className="w-5 h-5 animate-spin mr-2" />Loading finding details...</div>;
  }

  if (!finding) {
    return <div className="p-8 text-center text-destructive">Finding not found</div>;
  }

  const handleUpdateStatus = (status: "real" | "false_positive" | "informational" | "pending") => {
    updateFinding.mutate({ id: finding.id, data: { validation_status: status } });
  };

  const handleCreateRemediation = () => {
    createRemediation.mutate({
      data: {
        finding_id: finding.id,
        title: `Fix: ${finding.title}`,
        description: finding.recommended_fix || "Address the vulnerability described in the finding.",
        patch_snippet: "/* Add patch logic here */\n"
      }
    });
  };

  const cweNum = finding.cwe_id?.replace(/^CWE-/i, "") ?? "";
  const cveId = (finding as Record<string, unknown>).cve_id as string | undefined;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-start justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-2">
            <button onClick={() => history.back()} className="text-muted-foreground hover:text-foreground">
              <ArrowLeft className="w-4 h-4" />
            </button>
            <SeverityBadge severity={finding.severity} />
            <h1 className="text-2xl font-bold tracking-tight">{finding.title}</h1>
          </div>
          <div className="flex flex-wrap items-center gap-4 text-sm text-muted-foreground">
            <span className="flex items-center gap-1.5"><Target className="w-4 h-4" />{finding.target_url}</span>
            <span>Discovered: {format(new Date(finding.created_at), "MMM d, yyyy HH:mm")}</span>
            <Badge variant="secondary" className="text-[10px]">{finding.scanner_name}</Badge>
            {(finding as Record<string, unknown>).category && <Badge variant="outline" className="text-[10px]">{String((finding as Record<string, unknown>).category)}</Badge>}
          </div>
        </div>
        <div className="flex flex-col items-end gap-2 shrink-0">
          <div className="flex gap-2">
            {ghIssueUrl ? (
              <a href={ghIssueUrl} target="_blank" rel="noopener noreferrer">
                <Button variant="outline" size="sm" className="border-green-600 text-green-500">
                  <CheckCircle2 className="w-4 h-4 mr-1.5" /> View GitHub Issue
                </Button>
              </a>
            ) : (
              <Button variant="outline" size="sm" onClick={createGithubIssue} disabled={ghLoading} className="border-gray-600">
                {ghLoading ? <Loader2 className="w-4 h-4 mr-1.5 animate-spin" /> : <Github className="w-4 h-4 mr-1.5" />}
                {ghLoading ? "Creating..." : "GitHub Issue"}
              </Button>
            )}
            {ghError && <span className="text-xs text-red-400">{ghError}</span>}
          </div>
          <div className="flex gap-2 flex-wrap justify-end">
            {(["real", "false_positive", "informational"] as const).map(status => {
              const conf = {
                real: { label: "Valid", icon: <AlertTriangle className="w-4 h-4 mr-1" />, active: "bg-red-500 hover:bg-red-600 text-white" },
                false_positive: { label: "False Positive", icon: <XCircle className="w-4 h-4 mr-1" />, active: "bg-green-500 hover:bg-green-600 text-white" },
                informational: { label: "Info", icon: <Info className="w-4 h-4 mr-1" />, active: "bg-blue-500 hover:bg-blue-600 text-white" },
              }[status];
              return (
                <Button key={status}
                  variant={finding.validation_status === status ? "default" : "outline"} size="sm"
                  className={finding.validation_status === status ? conf.active : ""}
                  onClick={() => handleUpdateStatus(status)}>
                  {conf.icon}{conf.label}
                </Button>
              );
            })}
          </div>
        </div>
      </div>

      {/* KPI Cards */}
      <div className="grid gap-4 md:grid-cols-4">
        <Card>
          <CardHeader className="pb-2"><CardTitle className="text-sm text-muted-foreground font-medium">CVSS Score</CardTitle></CardHeader>
          <CardContent>
            <div className={`text-3xl font-bold font-mono ${(finding.cvss_score ?? 0) >= 9 ? "text-red-500" : (finding.cvss_score ?? 0) >= 7 ? "text-orange-500" : (finding.cvss_score ?? 0) >= 4 ? "text-yellow-500" : "text-blue-400"}`}>
              {finding.cvss_score ? finding.cvss_score.toFixed(1) : "N/A"}
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2"><CardTitle className="text-sm text-muted-foreground font-medium">CWE ID</CardTitle></CardHeader>
          <CardContent>
            <div className="flex items-center gap-2">
              <div className="text-2xl font-bold font-mono text-muted-foreground">{finding.cwe_id || "N/A"}</div>
              {cweNum && (
                <a href={`https://cwe.mitre.org/data/definitions/${cweNum}.html`} target="_blank" rel="noopener noreferrer"
                  className="text-muted-foreground hover:text-foreground"><ExternalLink className="w-3.5 h-3.5" /></a>
              )}
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2"><CardTitle className="text-sm text-muted-foreground font-medium">SLA Deadline</CardTitle></CardHeader>
          <CardContent>
            {(() => {
              const sev = finding.severity.toLowerCase();
              if (sev === "info") return <div className="text-lg font-bold font-mono text-muted-foreground">N/A</div>;
              const sla = getSlaStatus(sev, finding.created_at);
              return (
                <div>
                  <div className={`text-2xl font-bold font-mono ${sla.color}`}>{sla.label}</div>
                  {sla.deadline && <div className="text-[10px] text-muted-foreground mt-0.5">{format(sla.deadline, "MMM d, HH:mm")}</div>}
                </div>
              );
            })()}
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2"><CardTitle className="text-sm text-muted-foreground font-medium">Endpoint</CardTitle></CardHeader>
          <CardContent>
            <div className="text-xs font-mono truncate bg-muted/50 p-2 rounded border border-border">
              {finding.endpoint}
            </div>
            {cveId && (
              <div className="mt-2 flex items-center gap-1.5 text-xs">
                <Badge variant="outline" className="text-xs border-orange-500/40 text-orange-400">{cveId}</Badge>
                <a href={`https://nvd.nist.gov/vuln/detail/${cveId}`} target="_blank" rel="noopener noreferrer"
                  className="text-muted-foreground hover:text-orange-400"><ExternalLink className="w-3 h-3" /></a>
              </div>
            )}
          </CardContent>
        </Card>
      </div>

      {/* Tabs */}
      <Tabs defaultValue="details" className="w-full">
        <TabsList className="w-full justify-start border-b border-border rounded-none bg-transparent h-auto p-0 flex-wrap">
          {["details", "evidence", "remediation", "payloads", "patch"].map(tab => (
            <TabsTrigger key={tab} value={tab}
              className="rounded-none border-b-2 border-transparent data-[state=active]:border-primary data-[state=active]:bg-transparent px-5 py-3 capitalize">
              {tab}
            </TabsTrigger>
          ))}
        </TabsList>

        {/* Description */}
        <TabsContent value="details" className="pt-6 space-y-4">
          <Card>
            <CardHeader><CardTitle>Vulnerability Details</CardTitle></CardHeader>
            <CardContent>
              <div className="prose prose-sm dark:prose-invert max-w-none">
                {finding.description.split("\n\n").map((p, i) => <p key={i}>{p}</p>)}
              </div>
            </CardContent>
          </Card>
          {(finding as Record<string, unknown>).references && Array.isArray((finding as Record<string, unknown>).references) && (
            <Card>
              <CardHeader><CardTitle className="text-base">References</CardTitle></CardHeader>
              <CardContent>
                <ul className="space-y-1">
                  {((finding as Record<string, unknown>).references as string[]).map((ref, i) => (
                    <li key={i}>
                      <a href={ref} target="_blank" rel="noopener noreferrer"
                        className="text-sm text-primary hover:underline flex items-center gap-1.5">
                        <ExternalLink className="w-3 h-3 shrink-0" />{ref}
                      </a>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          )}
        </TabsContent>

        {/* Evidence */}
        <TabsContent value="evidence" className="pt-6">
          <Card>
            <CardHeader>
              <CardTitle>Proof of Concept / Evidence</CardTitle>
              <CardDescription>Raw HTTP requests, responses, or scanner output</CardDescription>
            </CardHeader>
            <CardContent>
              {finding.evidence ? (
                <pre className="p-4 bg-black/40 text-foreground font-mono text-xs overflow-x-auto rounded-md border border-border whitespace-pre-wrap break-all">
                  {finding.evidence}
                </pre>
              ) : (
                <div className="text-center py-12 text-muted-foreground">No specific evidence payload recorded.</div>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        {/* Remediation */}
        <TabsContent value="remediation" className="pt-6 space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Recommended Fix</CardTitle>
              <CardDescription>Guidance on how to resolve this vulnerability</CardDescription>
            </CardHeader>
            <CardContent>
              {finding.recommended_fix ? (
                <div className="prose prose-sm dark:prose-invert max-w-none mb-6">
                  {finding.recommended_fix.split("\n\n").map((p, i) => <p key={i}>{p}</p>)}
                </div>
              ) : (
                <div className="text-center py-6 text-muted-foreground mb-6">No specific remediation guidance provided.</div>
              )}
              <div className="border-t border-border pt-6 flex justify-between items-center">
                <div>
                  <h4 className="text-sm font-medium mb-1">Create Remediation Task</h4>
                  <p className="text-xs text-muted-foreground">Track the resolution of this vulnerability.</p>
                </div>
                <Button onClick={handleCreateRemediation} disabled={createRemediation.isPending}>
                  <Wrench className="w-4 h-4 mr-2" />
                  {createRemediation.isPending ? "Creating..." : "Track Remediation"}
                </Button>
              </div>
            </CardContent>
          </Card>

          <AiStreamPanel
            endpoint={`/api/ai/finding-advice/${findingId}`}
            buttonLabel="Get AI Advice"
            icon={<Wrench className="w-4 h-4" />}
            title="AI Remediation Advice"
            description="Claude-powered step-by-step fix guidance for this vulnerability"
            emptyText={`Click "Get AI Advice" for specific, developer-friendly fix instructions powered by Claude.`}
          />
        </TabsContent>

        {/* Attack Payloads */}
        <TabsContent value="payloads" className="pt-6">
          <AiStreamPanel
            endpoint={`/api/ai/payloads/${findingId}`}
            buttonLabel="Generate Payloads"
            icon={<Zap className="w-4 h-4" />}
            title="AI Attack Payload Generator"
            description="Generate specific, targeted attack payloads for authorized penetration testing"
            emptyText={`Click "Generate Payloads" to create targeted attack payloads for this vulnerability. For authorized testing only.`}
          />
        </TabsContent>

        {/* Code Patch */}
        <TabsContent value="patch" className="pt-6">
          <AiStreamPanel
            endpoint={`/api/ai/patch/${findingId}`}
            buttonLabel="Generate Patch"
            icon={<Code2 className="w-4 h-4" />}
            title="AI Code Patch Generator"
            description="Production-ready code fix with before/after examples and a security test"
            emptyText={`Click "Generate Patch" to get a code-level fix with vulnerable → fixed examples and test cases.`}
          />
        </TabsContent>
      </Tabs>
    </div>
  );
}
