import { useState, useEffect, useRef } from "react";
import { useParams, Link, useLocation } from "wouter";
import { 
  useGetScanJob, 
  useGetScanJobFindings,
  useGetScanJobAttackSurface
} from "@workspace/api-client-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Download, AlertTriangle, Info, Clock, Activity, FileText, CheckCircle2, XCircle, Radio, Loader2 } from "lucide-react";
import { format } from "date-fns";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

function AISummaryTab({ scanId, isRunning }: { scanId: string; isRunning: boolean }) {
  const [summary, setSummary] = useState("");
  const [loading, setLoading] = useState(false);
  const [done, setDone] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function generate() {
    setSummary(""); setDone(false); setError(null); setLoading(true);
    try {
      const res = await fetch(`/api/ai/scan-summary/${scanId}`, {
        method: "POST", credentials: "include",
      });
      if (!res.ok) throw new Error("Request failed");
      const reader = res.body!.getReader();
      const decoder = new TextDecoder();
      let buf = "";
      while (true) {
        const { done: doneReading, value } = await reader.read();
        if (doneReading) break;
        buf += decoder.decode(value, { stream: true });
        const lines = buf.split("\n");
        buf = lines.pop() ?? "";
        for (const line of lines) {
          if (!line.startsWith("data: ")) continue;
          try {
            const d = JSON.parse(line.slice(6));
            if (d.content) setSummary(p => p + d.content);
            if (d.done) setDone(true);
            if (d.error) setError(d.error);
          } catch { /* ignore */ }
        }
      }
    } catch (err) {
      setError("Failed to connect to AI service");
    } finally { setLoading(false); }
  }

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between">
        <div>
          <CardTitle>AI Executive Summary</CardTitle>
          <CardDescription>Claude-powered security assessment of this scan's findings</CardDescription>
        </div>
        <Button onClick={generate} disabled={loading || isRunning} size="sm"
          className="bg-violet-600 hover:bg-violet-700 text-white">
          {loading ? <><Loader2 className="w-4 h-4 mr-2 animate-spin" />Generating…</> : <><Activity className="w-4 h-4 mr-2" />Generate Summary</>}
        </Button>
      </CardHeader>
      <CardContent>
        {error && <p className="text-red-400 text-sm mb-4">{error}</p>}
        {!summary && !loading && !error && (
          <div className="text-center py-12 text-muted-foreground">
            {isRunning
              ? "Wait for the scan to complete, then generate an AI summary."
              : "Click \"Generate Summary\" to get an AI-powered executive assessment of this scan's findings."}
          </div>
        )}
        {(summary || loading) && (
          <div className="prose prose-sm dark:prose-invert max-w-none leading-relaxed">
            {summary.split("\n\n").map((p, i) => p.trim() && <p key={i}>{p}</p>)}
            {loading && <span className="inline-block w-2 h-4 bg-violet-400 animate-pulse ml-1 align-middle" />}
          </div>
        )}
        {done && (
          <p className="text-xs text-muted-foreground mt-4 pt-4 border-t border-border">
            Generated by Claude Sonnet · Powered by Replit AI Integrations
          </p>
        )}
      </CardContent>
    </Card>
  );
}

function SeverityBadge({ severity }: { severity: string }) {
  const colors: Record<string, string> = {
    critical: "bg-[hsl(var(--critical))] text-white",
    high: "bg-[hsl(var(--high))] text-white",
    medium: "bg-[hsl(var(--medium))] text-black",
    low: "bg-[hsl(var(--low))] text-black",
    info: "bg-[hsl(var(--info))] text-white",
  };
  
  return (
    <Badge className={`${colors[severity.toLowerCase()]} border-none uppercase text-[10px]`}>
      {severity}
    </Badge>
  );
}

export default function ScanDetail() {
  const params = useParams();
  const [, setLocation] = useLocation();
  const scanId = params.id as string;

  const { data: scan, isLoading: scanLoading } = useGetScanJob(scanId, {
    query: {
      refetchInterval: (query) => {
        const status = query.state.data?.status;
        return (status === 'queued' || status === 'running') ? 3000 : false;
      }
    }
  });

  const { data: findings, isLoading: findingsLoading, refetch: refetchFindings } = useGetScanJobFindings(scanId, {
    query: {
      refetchInterval: 3000,
    }
  });
  const { data: attackSurface } = useGetScanJobAttackSurface(scanId);

  type LogLine = { kind: "log" | "engine" | "finding" | "error"; text: string; time: string };
  const [sseLog, setSseLog] = useState<LogLine[]>([]);
  const [sseActive, setSseActive] = useState(false);
  const [activeEngine, setActiveEngine] = useState<string | null>(null);
  const sseRef = useRef<EventSource | null>(null);
  const logEndRef = useRef<HTMLDivElement | null>(null);

  const appendLog = (kind: LogLine["kind"], text: string) => {
    const time = new Date().toLocaleTimeString("en-US", { hour12: false, hour: "2-digit", minute: "2-digit", second: "2-digit" });
    setSseLog(p => [...p, { kind, text, time }]);
    setTimeout(() => logEndRef.current?.scrollIntoView({ behavior: "smooth" }), 50);
  };

  function startSSE() {
    if (sseRef.current) { sseRef.current.close(); }
    setSseLog([]);
    setSseActive(true);
    setActiveEngine(null);

    const es = new EventSource(`/api/scan-jobs/${scanId}/stream`);
    sseRef.current = es;

    es.addEventListener("log", (e: MessageEvent) => {
      try { const d = JSON.parse(e.data); appendLog("log", d.message ?? ""); } catch { /* */ }
    });
    es.addEventListener("engine", (e: MessageEvent) => {
      try {
        const d = JSON.parse(e.data);
        if (d.status === "scanning") {
          setActiveEngine(d.engine);
          appendLog("engine", `▶ ${d.engine} — ${d.message ?? "scanning"}`);
        } else {
          setActiveEngine(null);
          appendLog("engine", `✓ ${d.engine} — ${d.message ?? "done"}`);
        }
      } catch { /* */ }
    });
    es.addEventListener("finding", (e: MessageEvent) => {
      try {
        const d = JSON.parse(e.data);
        const sev = (d.severity ?? "info").toUpperCase();
        appendLog("finding", `[${sev}] ${d.title} @ ${d.endpoint ?? ""}`);
        refetchFindings();
      } catch { /* */ }
    });
    es.addEventListener("progress", (e: MessageEvent) => {
      try {
        const d = JSON.parse(e.data);
        if (d.progress !== undefined) appendLog("log", `Progress: ${d.progress}%`);
      } catch { /* */ }
    });
    es.addEventListener("complete", (e: MessageEvent) => {
      try {
        const d = JSON.parse(e.data);
        appendLog("log", `✅ ${d.message ?? "Scan complete"}`);
      } catch { /* */ }
      setSseActive(false);
      setActiveEngine(null);
      es.close();
      sseRef.current = null;
      refetchFindings();
    });
    es.addEventListener("error", (e: MessageEvent) => {
      try {
        const d = JSON.parse(e.data);
        appendLog("error", `❌ Error: ${d.message ?? "Scan failed"}`);
      } catch { /* */ }
      setSseActive(false);
      setActiveEngine(null);
      es.close();
      sseRef.current = null;
    });
    es.onerror = () => {
      if (es.readyState === EventSource.CLOSED) {
        setSseActive(false);
        setActiveEngine(null);
        sseRef.current = null;
      }
    };
  }

  // Auto-start SSE when scan is running
  useEffect(() => {
    if (scan?.status === "running" && !sseRef.current) {
      startSSE();
    }
    if (scan?.status === "completed" || scan?.status === "failed") {
      if (sseRef.current) {
        sseRef.current.close();
        sseRef.current = null;
        setSseActive(false);
      }
      refetchFindings();
    }
  }, [scan?.status]);

  function exportJSON() {
    const blob = new Blob([JSON.stringify({ scan, findings }, null, 2)], { type: "application/json" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `scan-${scanId}.json`;
    a.click();
  }

  function exportPDF() {
    if (!scan) return;
    const doc = new jsPDF();
    doc.setFontSize(20);
    doc.text("Bug Finder Pro — Scan Report", 14, 22);
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Target: ${scan.target_url}`, 14, 32);
    doc.text(`Status: ${scan.status} | Risk Score: ${scan.risk_score}/100`, 14, 38);
    doc.text(`Date: ${format(new Date(scan.created_at), "MMM d, yyyy HH:mm")}`, 14, 44);
    doc.text(`Critical: ${scan.critical_count} | High: ${scan.high_count} | Medium: ${scan.medium_count}`, 14, 50);

    const rows = (Array.isArray(findings) ? findings : []).map((f: Record<string, unknown>) => [
      String(f.title ?? "").slice(0, 50),
      String(f.severity ?? "").toUpperCase(),
      String(f.cvss_score ?? "N/A"),
      String(f.cwe_id ?? ""),
      String(f.endpoint ?? "").slice(0, 40),
    ]);

    autoTable(doc, {
      startY: 58,
      head: [["Title", "Severity", "CVSS", "CWE", "Endpoint"]],
      body: rows,
      styles: { fontSize: 8 },
      headStyles: { fillColor: [109, 40, 217] },
    });

    doc.save(`scan-${scanId}-report.pdf`);
  }

  if (scanLoading) {
    return <div className="p-8 flex justify-center text-muted-foreground">Loading scan details...</div>;
  }

  if (!scan) {
    return <div className="p-8 text-center text-destructive">Scan not found</div>;
  }

  const isRunning = scan.status === 'running' || scan.status === 'queued';

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center space-x-3 mb-1">
            <h1 className="text-3xl font-bold tracking-tight font-mono">{scan.target_url}</h1>
            <Badge variant="outline" className={`capitalize ${
              scan.status === 'running' ? 'bg-blue-500/10 text-blue-500 border-blue-500/20 animate-pulse' :
              scan.status === 'completed' ? 'bg-green-500/10 text-green-500 border-green-500/20' :
              scan.status === 'failed' ? 'bg-destructive/10 text-destructive border-destructive/20' :
              'bg-muted text-muted-foreground'
            }`}>
              {scan.status}
            </Badge>
          </div>
          <p className="text-muted-foreground flex items-center">
            <Clock className="w-4 h-4 mr-1.5" />
            Started {format(new Date(scan.created_at), "MMM d, yyyy HH:mm")}
          </p>
        </div>
        <div className="flex items-center space-x-2 flex-wrap gap-y-2">
          <Button variant="outline" onClick={exportJSON}>
            <Download className="w-4 h-4 mr-2" />
            Export JSON
          </Button>
          <Button variant="outline" onClick={exportPDF} disabled={isRunning}>
            <FileText className="w-4 h-4 mr-2" />
            PDF Report
          </Button>
          <Button variant="outline" onClick={startSSE} disabled={sseActive}>
            {sseActive ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Radio className="w-4 h-4 mr-2" />}
            {sseActive ? "Streaming…" : "Live Stream"}
          </Button>
        </div>
      </div>

      {isRunning && (
        <Card className="border-blue-500/20 bg-blue-500/5">
          <CardContent className="pt-6">
            <div className="flex items-center justify-between mb-2">
              <span className="text-sm font-medium text-blue-500 flex items-center gap-2">
                <Loader2 className="w-3.5 h-3.5 animate-spin" />
                {activeEngine ? `Running: ${activeEngine}` : "Scan in progress…"}
              </span>
              <span className="text-sm font-mono text-blue-500">{scan.progress}%</span>
            </div>
            <Progress value={scan.progress} className="h-2 [&>div]:bg-blue-500" />
            <p className="text-xs text-blue-400/60 mt-2">
              {scan.findings_count > 0
                ? `${scan.findings_count} finding(s) detected so far (${scan.critical_count} critical, ${scan.high_count} high)`
                : "Scanning target for vulnerabilities…"}
            </p>
          </CardContent>
        </Card>
      )}

      {(sseLog.length > 0 || sseActive) && (
        <Card className="border-violet-500/20 bg-violet-500/5">
          <CardHeader className="pb-2 pt-4 px-4">
            <CardTitle className="text-sm flex items-center gap-2">
              {sseActive && <Radio className="w-3.5 h-3.5 text-violet-400 animate-pulse" />}
              Live Scan Stream
              {activeEngine && (
                <span className="text-xs font-normal text-violet-300 bg-violet-500/10 px-2 py-0.5 rounded-full">
                  {activeEngine}
                </span>
              )}
            </CardTitle>
          </CardHeader>
          <CardContent className="px-4 pb-4">
            <div className="font-mono text-xs bg-black/60 rounded p-3 max-h-64 overflow-y-auto leading-relaxed space-y-0.5">
              {sseActive && sseLog.length === 0 && (
                <span className="text-violet-400/70 animate-pulse">Connecting to scanner…</span>
              )}
              {sseLog.map((line, i) => (
                <div key={i} className={
                  line.kind === "engine" ? "text-cyan-300 font-semibold" :
                  line.kind === "finding" ? (
                    line.text.includes("[CRITICAL]") ? "text-red-400 font-bold" :
                    line.text.includes("[HIGH]") ? "text-orange-400 font-semibold" :
                    line.text.includes("[MEDIUM]") ? "text-yellow-400" :
                    "text-green-400"
                  ) :
                  line.kind === "error" ? "text-red-500" :
                  "text-violet-300/80"
                }>
                  <span className="text-violet-500/50 mr-2 select-none">{line.time}</span>
                  {line.text}
                </div>
              ))}
              <div ref={logEndRef} />
            </div>
          </CardContent>
        </Card>
      )}

      <div className="grid gap-4 md:grid-cols-4">
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm text-muted-foreground font-medium">Risk Score</CardTitle>
          </CardHeader>
          <CardContent>
            <div className={`text-3xl font-bold ${
              scan.risk_score > 80 ? 'text-[hsl(var(--critical))]' :
              scan.risk_score > 60 ? 'text-[hsl(var(--high))]' :
              scan.risk_score > 30 ? 'text-[hsl(var(--medium))]' :
              'text-[hsl(var(--low))]'
            }`}>{scan.risk_score}/100</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm text-muted-foreground font-medium">Critical</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold text-[hsl(var(--critical))]">{scan.critical_count}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm text-muted-foreground font-medium">High</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold text-[hsl(var(--high))]">{scan.high_count}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm text-muted-foreground font-medium">Medium</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold text-[hsl(var(--medium))]">{scan.medium_count}</div>
          </CardContent>
        </Card>
      </div>

      <Tabs defaultValue="findings" className="w-full">
        <TabsList className="w-full justify-start border-b border-border rounded-none bg-transparent h-auto p-0">
          <TabsTrigger value="findings" className="rounded-none border-b-2 border-transparent data-[state=active]:border-primary data-[state=active]:bg-transparent px-6 py-3">
            Findings ({scan.findings_count})
          </TabsTrigger>
          <TabsTrigger value="summary" className="rounded-none border-b-2 border-transparent data-[state=active]:border-primary data-[state=active]:bg-transparent px-6 py-3">
            AI Summary
          </TabsTrigger>
          <TabsTrigger value="surface" className="rounded-none border-b-2 border-transparent data-[state=active]:border-primary data-[state=active]:bg-transparent px-6 py-3">
            Attack Surface
          </TabsTrigger>
          <TabsTrigger value="config" className="rounded-none border-b-2 border-transparent data-[state=active]:border-primary data-[state=active]:bg-transparent px-6 py-3">
            Configuration
          </TabsTrigger>
        </TabsList>
        
        <TabsContent value="findings" className="pt-6">
          <Card>
            <div className="rounded-md border-0">
              <table className="w-full text-sm text-left">
                <thead className="text-xs text-muted-foreground uppercase bg-muted/50">
                  <tr>
                    <th className="px-4 py-3">Severity</th>
                    <th className="px-4 py-3">Title</th>
                    <th className="px-4 py-3">Category</th>
                    <th className="px-4 py-3">Endpoint</th>
                    <th className="px-4 py-3 text-right">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border">
                  {findingsLoading ? (
                    <tr>
                      <td colSpan={5} className="px-4 py-8 text-center text-muted-foreground">Loading findings...</td>
                    </tr>
                  ) : (findings?.items?.length ?? 0) === 0 ? (
                    <tr>
                      <td colSpan={5} className="px-4 py-8 text-center text-muted-foreground">
                        {isRunning ? "No findings discovered yet..." : "No vulnerabilities found. System secure."}
                      </td>
                    </tr>
                  ) : (
                    findings?.items?.map((finding) => (
                      <tr key={finding.id} className="hover:bg-muted/20 cursor-pointer" onClick={() => setLocation(`/findings/${finding.id}`)}>
                        <td className="px-4 py-3 w-24">
                          <SeverityBadge severity={finding.severity} />
                        </td>
                        <td className="px-4 py-3 font-medium">{finding.title}</td>
                        <td className="px-4 py-3 text-muted-foreground text-xs">{finding.category}</td>
                        <td className="px-4 py-3 font-mono text-xs max-w-[200px] truncate" title={finding.endpoint}>
                          {finding.endpoint}
                        </td>
                        <td className="px-4 py-3 text-right">
                          <Badge variant="outline" className="text-[10px] capitalize">
                            {finding.validation_status.replace('_', ' ')}
                          </Badge>
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          </Card>
        </TabsContent>
        
        <TabsContent value="summary" className="pt-6">
          <AISummaryTab scanId={scanId} isRunning={isRunning} />
        </TabsContent>

        <TabsContent value="surface" className="pt-6">
          <Card>
            <CardHeader>
              <CardTitle>Attack Surface Map</CardTitle>
              <CardDescription>Discovered nodes and relationships</CardDescription>
            </CardHeader>
            <CardContent>
              {attackSurface ? (
                <div className="space-y-4">
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
                    <div className="p-4 bg-muted/50 rounded-md">
                      <div className="text-2xl font-bold">{attackSurface.nodes.filter(n => n.type === 'domain').length}</div>
                      <div className="text-xs text-muted-foreground uppercase">Domains</div>
                    </div>
                    <div className="p-4 bg-muted/50 rounded-md">
                      <div className="text-2xl font-bold">{attackSurface.nodes.filter(n => n.type === 'endpoint').length}</div>
                      <div className="text-xs text-muted-foreground uppercase">Endpoints</div>
                    </div>
                    <div className="p-4 bg-muted/50 rounded-md">
                      <div className="text-2xl font-bold">{attackSurface.nodes.filter(n => n.type === 'parameter').length}</div>
                      <div className="text-xs text-muted-foreground uppercase">Parameters</div>
                    </div>
                    <div className="p-4 bg-muted/50 rounded-md">
                      <div className="text-2xl font-bold">{attackSurface.edges.length}</div>
                      <div className="text-xs text-muted-foreground uppercase">Connections</div>
                    </div>
                  </div>
                  {/* Simplistic representation of attack surface data */}
                  <div className="border border-border rounded-md overflow-hidden">
                    <table className="w-full text-sm">
                      <thead className="bg-muted/50 text-xs uppercase text-muted-foreground">
                        <tr>
                          <th className="px-4 py-2 text-left">Node Type</th>
                          <th className="px-4 py-2 text-left">Identifier</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-border">
                        {attackSurface.nodes.slice(0, 20).map(node => (
                          <tr key={node.id}>
                            <td className="px-4 py-2"><Badge variant="outline" className="text-[10px]">{node.type}</Badge></td>
                            <td className="px-4 py-2 font-mono text-xs">{node.label}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                    {attackSurface.nodes.length > 20 && (
                      <div className="p-2 text-center text-xs text-muted-foreground bg-muted/20 border-t border-border">
                        Showing 20 of {attackSurface.nodes.length} nodes
                      </div>
                    )}
                  </div>
                </div>
              ) : (
                <div className="text-center py-12 text-muted-foreground">
                  {isRunning ? "Mapping attack surface..." : "No attack surface data available."}
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="config" className="pt-6">
          <Card>
            <CardHeader>
              <CardTitle>Scan Configuration</CardTitle>
            </CardHeader>
            <CardContent>
              <dl className="grid grid-cols-1 md:grid-cols-2 gap-x-4 gap-y-6 text-sm">
                <div>
                  <dt className="text-muted-foreground font-medium mb-1">Target URL</dt>
                  <dd className="font-mono">{scan.target_url}</dd>
                </div>
                <div>
                  <dt className="text-muted-foreground font-medium mb-1">Profile</dt>
                  <dd className="uppercase tracking-wide">{scan.scan_profile}</dd>
                </div>
                <div>
                  <dt className="text-muted-foreground font-medium mb-1">Engines Used</dt>
                  <dd className="flex gap-2">
                    {scan.scanner_engines.map(engine => (
                      <Badge key={engine} variant="secondary" className="capitalize">{engine}</Badge>
                    ))}
                  </dd>
                </div>
                <div>
                  <dt className="text-muted-foreground font-medium mb-1">Options</dt>
                  <dd className="space-y-1">
                    <div className="flex items-center">
                      {scan.validation_enabled ? <CheckCircle2 className="w-4 h-4 text-green-500 mr-2" /> : <XCircle className="w-4 h-4 text-muted-foreground mr-2" />}
                      <span>Validation</span>
                    </div>
                    <div className="flex items-center">
                      {scan.fuzzing_enabled ? <CheckCircle2 className="w-4 h-4 text-green-500 mr-2" /> : <XCircle className="w-4 h-4 text-muted-foreground mr-2" />}
                      <span>Active Fuzzing</span>
                    </div>
                    <div className="flex items-center">
                      {scan.bug_bounty_mode ? <CheckCircle2 className="w-4 h-4 text-green-500 mr-2" /> : <XCircle className="w-4 h-4 text-muted-foreground mr-2" />}
                      <span>Bug Bounty Mode</span>
                    </div>
                  </dd>
                </div>
              </dl>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}
