import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import dashboardRouter from "./dashboard";
import scansRouter from "./scans";
import findingsRouter from "./findings";
import targetsRouter from "./targets";
import settingsRouter from "./settings";
import remediationsRouter from "./remediations";
import streamRouter from "./stream";
import auditLogRouter from "./auditlog";
import webhooksRouter from "./webhooks";
import integrationsRouter from "./integrations";
import analyticsRouter from "./analytics";
import aiRouter from "./ai";
import scanTemplatesRouter from "./scan-templates";
import complianceRouter from "./compliance";
import comparisonRouter from "./comparison";
import slaRouter from "./sla";
import reportSchedulesRouter from "./report-schedules";
import commentsRouter from "./comments";
import riskTrendRouter from "./risk-trend";
import searchRouter from "./search";
import reportsRouter from "./reports";
import notificationsRouter from "./notifications";
import apiKeysRouter from "./api-keys";
import scannerRulesRouter from "./scanner-rules";
import certsRouter from "./certs";
import webhookLogRouter from "./webhook-log";
import dashboardLayoutRouter from "./dashboard-layout";
import scheduledScansRouter from "./scheduled-scans";
import analyticsMetricsRouter from "./analytics-metrics";
import engagementsRouter from "./engagements";
import testsRouter from "./tests";
import webhookTriggersRouter from "./webhook-triggers";
import complianceReportsRouter from "./compliance-reports";
import apiVersionRouter from "./api-version";
import oidcSsoRouter from "./oidc-sso";
import projectRbacRouter from "./project-rbac";
import adminRouter from "./admin";
import credentialsRouter from "./credentials";
import cicdRouter from "./cicd";
import suppressionRouter from "./suppression";
import oidcRouter from "./oidc";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(dashboardRouter);
router.use(scansRouter);
router.use(findingsRouter);
router.use(targetsRouter);
router.use(settingsRouter);
router.use(remediationsRouter);
router.use(streamRouter);
router.use(auditLogRouter);
router.use(webhooksRouter);
router.use(integrationsRouter);
router.use(analyticsRouter);
router.use(aiRouter);
router.use(scanTemplatesRouter);
router.use(complianceRouter);
router.use(comparisonRouter);
router.use(slaRouter);
router.use(reportSchedulesRouter);
router.use(commentsRouter);
router.use(riskTrendRouter);
router.use(searchRouter);
router.use(reportsRouter);
router.use(notificationsRouter);
router.use(apiKeysRouter);
router.use(scannerRulesRouter);
router.use(certsRouter);
router.use(webhookLogRouter);
router.use(dashboardLayoutRouter);
router.use(scheduledScansRouter);
router.use(analyticsMetricsRouter);
router.use(engagementsRouter);
router.use(testsRouter);
router.use(webhookTriggersRouter);
router.use(complianceReportsRouter);
router.use(apiVersionRouter);
router.use(oidcSsoRouter);
router.use(projectRbacRouter);

export default router;
