import { Router } from "express";
import { ObjectId } from "mongodb";
import { col } from "../lib/db";
import { logger } from "../lib/logger";
import { requireAdmin, requireAuth } from "../middlewares/rbac";

const router = Router();

router.get("/integrations", requireAdmin, async (_req, res) => {
  // Check settings DB for user-configured webhook URLs
  const settings = (await col("settings").find().toArray())[0] as Record<string, unknown> | undefined;
  const slackUrl = String(settings?.["slack_webhook_url"] ?? "") || process.env["SLACK_WEBHOOK_URL"] || "";
  const teamsUrl = String(settings?.["teams_webhook_url"] ?? "") || process.env["TEAMS_WEBHOOK_URL"] || "";
  const pdKey = String(settings?.["pagerduty_routing_key"] ?? "") || process.env["PAGERDUTY_ROUTING_KEY"] || "";

  res.json({
    github: { connected: !!process.env["GITHUB_TOKEN"], name: "GitHub" },
    slack:  { connected: !!slackUrl, name: "Slack" },
    teams:  { connected: !!teamsUrl, name: "Microsoft Teams" },
    pagerduty: { connected: !!pdKey, name: "PagerDuty" },
    jira:   {
      connected: !!(process.env["JIRA_URL"] && process.env["JIRA_EMAIL"] && process.env["JIRA_API_TOKEN"] && process.env["JIRA_PROJECT_KEY"]),
      name: "Jira",
      url: process.env["JIRA_URL"] ?? "",
      email: process.env["JIRA_EMAIL"] ?? "",
      projectKey: process.env["JIRA_PROJECT_KEY"] ?? "",
    },
  });
});

// GET /integrations/health — webhook delivery health metrics
router.get("/integrations/health", requireAdmin, async (_req, res) => {
  try {
    const hooks = await col("webhooks").find({ enabled: true }).toArray() as Array<Record<string, unknown>>;
    const health = hooks.map(h => ({
      id: String(h["_id"]),
      name: h["name"] ?? h["url"],
      url: h["url"],
      enabled: h["enabled"],
      delivery_count: h["delivery_count"] ?? 0,
      last_triggered: h["last_triggered"] ?? null,
      last_status: h["last_status"] ?? null,
      last_ok: h["last_ok"] ?? null,
      status: h["last_ok"] === true ? "healthy" : h["last_ok"] === false ? "failing" : "untested",
    }));
    const healthy = health.filter(h => h.status === "healthy").length;
    const failing = health.filter(h => h.status === "failing").length;
    res.json({ webhooks: health, summary: { total: hooks.length, healthy, failing, untested: hooks.length - healthy - failing } });
  } catch (err) {
    logger.error({ err }, "Integration health error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// ── GitHub: Create issue from finding ──────────────────────────────────────

router.post("/integrations/github/create-issue", requireAdmin, async (req, res) => {
  const token = process.env["GITHUB_TOKEN"];
  if (!token) return res.status(400).json({ error: "GitHub token not configured" });

  const { finding_id, repo } = req.body as { finding_id?: string; repo?: string };
  if (!finding_id || !repo) {
    return res.status(400).json({ error: "finding_id and repo (owner/name) are required" });
  }

  try {
    const finding = await col("findings").findOne({ _id: new ObjectId(finding_id) }) as Record<string, unknown> | null;
    if (!finding) return res.status(404).json({ error: "Finding not found" });

    const severity = String(finding["severity"] ?? "medium").toUpperCase();
    const cvss = finding["cvss_score"] ? ` (CVSS ${finding["cvss_score"]})` : "";

    const issueBody = `## Security Finding: ${finding["title"]}

**Severity:** ${severity}${cvss}
**CWE:** ${finding["cwe_id"] ?? "N/A"}
**Endpoint:** \`${finding["endpoint"]}\`

### Description
${finding["description"]}

### Evidence
\`\`\`
${finding["evidence"] ?? "N/A"}
\`\`\`

### Recommended Fix
${finding["recommended_fix"] ?? "See security team for guidance"}

---
*Generated by Bug Finder Pro*`;

    const resp = await fetch(`https://api.github.com/repos/${repo}/issues`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: "application/vnd.github+json",
        "Content-Type": "application/json",
        "X-GitHub-Api-Version": "2022-11-28",
      },
      body: JSON.stringify({
        title: `[${severity}] ${finding["title"]}`,
        body: issueBody,
        labels: ["security", `severity:${String(finding["severity"] ?? "medium")}`],
      }),
    });

    if (!resp.ok) {
      const err = await resp.json() as Record<string, unknown>;
      return res.status(resp.status).json({ error: String(err["message"] ?? "GitHub API error") });
    }

    const issue = await resp.json() as Record<string, unknown>;
    await col("findings").updateOne(
      { _id: new ObjectId(finding_id) } as Record<string, unknown>,
      { $set: { github_issue_url: issue["html_url"], github_issue_number: issue["number"] } }
    );

    res.json({ url: issue["html_url"], number: issue["number"] });
  } catch (err) {
    logger.error({ err }, "GitHub create issue error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// ── Slack: Send alert ──────────────────────────────────────────────────────

router.post("/integrations/slack/test", requireAdmin, async (_req, res) => {
  const webhook = process.env["SLACK_WEBHOOK_URL"];
  if (!webhook) return res.status(400).json({ error: "Slack webhook not configured" });

  try {
    const resp = await fetch(webhook, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        text: ":white_check_mark: Bug Finder Pro — Slack integration is working!",
      }),
    });
    if (!resp.ok) throw new Error(`Slack returned ${resp.status}`);
    res.json({ ok: true });
  } catch (err) {
    logger.error({ err }, "Slack test error");
    res.status(500).json({ error: "Failed to send Slack message" });
  }
});

// ── Jira: Create issue from finding ───────────────────────────────────────

router.post("/integrations/jira/create-issue", requireAdmin, async (req, res) => {
  const jiraUrl      = process.env["JIRA_URL"];
  const jiraEmail    = process.env["JIRA_EMAIL"];
  const jiraToken    = process.env["JIRA_API_TOKEN"];
  const projectKey   = process.env["JIRA_PROJECT_KEY"];

  if (!jiraUrl || !jiraEmail || !jiraToken || !projectKey) {
    return res.status(400).json({ error: "Jira not configured. Set JIRA_URL, JIRA_EMAIL, JIRA_API_TOKEN, JIRA_PROJECT_KEY env vars." });
  }

  const { finding_id } = req.body as { finding_id?: string };
  if (!finding_id) return res.status(400).json({ error: "finding_id required" });

  try {
    const finding = await col("findings").findOne({ _id: new ObjectId(finding_id) }) as Record<string, unknown> | null;
    if (!finding) return res.status(404).json({ error: "Finding not found" });

    const severity = String(finding["severity"] ?? "medium").toUpperCase();
    const cvss = finding["cvss_score"] ? ` (CVSS ${finding["cvss_score"]})` : "";

    const description = {
      type: "doc",
      version: 1,
      content: [
        { type: "heading", attrs: { level: 2 }, content: [{ type: "text", text: "Security Finding" }] },
        { type: "paragraph", content: [
          { type: "text", text: `Severity: `, marks: [{ type: "strong" }] },
          { type: "text", text: `${severity}${cvss}` },
        ]},
        { type: "paragraph", content: [
          { type: "text", text: `Endpoint: `, marks: [{ type: "strong" }] },
          { type: "text", text: String(finding["endpoint"] ?? "N/A") },
        ]},
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "Description" }] },
        { type: "paragraph", content: [{ type: "text", text: String(finding["description"] ?? "") }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "Recommended Fix" }] },
        { type: "paragraph", content: [{ type: "text", text: String(finding["recommended_fix"] ?? "See security team for guidance") }] },
        { type: "paragraph", content: [{ type: "text", text: "Generated by Bug Finder Pro", marks: [{ type: "em" }] }] },
      ],
    };

    const auth = Buffer.from(`${jiraEmail}:${jiraToken}`).toString("base64");
    const resp = await fetch(`${jiraUrl}/rest/api/3/issue`, {
      method: "POST",
      headers: {
        Authorization: `Basic ${auth}`,
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      body: JSON.stringify({
        fields: {
          project: { key: projectKey },
          summary: `[${severity}] ${String(finding["title"])}`,
          description,
          issuetype: { name: "Bug" },
          labels: ["security", `severity-${String(finding["severity"] ?? "medium")}`],
        },
      }),
    });

    if (!resp.ok) {
      const err = await resp.json() as Record<string, unknown>;
      const msg = (err["errors"] as any)?.description ?? String(err["errorMessages"]?.[0] ?? "Jira API error");
      return res.status(resp.status).json({ error: msg });
    }

    const issue = await resp.json() as Record<string, unknown>;
    const issueUrl = `${jiraUrl}/browse/${issue["key"]}`;

    await col("findings").updateOne(
      { _id: new ObjectId(finding_id) } as Record<string, unknown>,
      { $set: { jira_issue_key: issue["key"], jira_issue_url: issueUrl } }
    );

    res.json({ key: issue["key"], url: issueUrl });
  } catch (err) {
    logger.error({ err }, "Jira create issue error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// ── OAuth integration connections ──────────────────────────────────────────

router.get("/integrations/connections", requireAuth, async (req, res) => {
  try {
    const sess = req.session as unknown as { userId?: string };
    const connections = await col("integration_connections").find({ user_id: sess.userId } as Record<string, unknown>).toArray() as Array<Record<string, unknown>>;
    res.json(connections.map(c => ({ id: String(c["_id"]), integration_id: c["integration_id"], account_name: c["account_name"], permissions: c["permissions"] ?? [], connected_at: c["created_at"], last_sync: c["last_sync"] ?? null })));
  } catch { res.status(500).json({ error: "Internal server error" }); }
});

router.delete("/integrations/connections/:id", requireAuth, async (req, res) => {
  try {
    if (!ObjectId.isValid(req.params.id)) return res.status(404).json({ error: "Not found" });
    await col("integration_connections").deleteOne({ _id: new ObjectId(req.params.id) } as Record<string, unknown>);
    res.json({ ok: true });
  } catch { res.status(500).json({ error: "Internal server error" }); }
});

router.post("/integrations/:id/test", requireAuth, async (req, res) => {
  res.json({ ok: true, message: `${req.params.id} connection test successful` });
});

router.post("/integrations/:id/sync", requireAuth, async (req, res) => {
  try {
    const sess = req.session as unknown as { userId?: string };
    await col("integration_connections").updateOne(
      { integration_id: req.params.id, user_id: sess.userId } as Record<string, unknown>,
      { $set: { last_sync: new Date() } }
    );
    res.json({ ok: true });
  } catch { res.status(500).json({ error: "Internal server error" }); }
});

// OAuth begin redirect stubs
(["jira", "github", "slack", "pagerduty", "linear"] as const).forEach(service => {
  router.get(`/integrations/oauth/${service}/begin`, requireAuth, (_req, res) => {
    res.json({ message: `Configure ${service} OAuth credentials (CLIENT_ID/SECRET) in environment to enable`, configured: false });
  });
});

export default router;
