import { Router } from "express";
import { ObjectId } from "mongodb";
import { col } from "../lib/db";
import { logger } from "../lib/logger";
import { requireAdmin, requireAuth } from "../middlewares/rbac";

const router = Router();

router.get("/integrations", requireAdmin, async (_req, res) => {
  // Check settings DB for user-configured webhook URLs
  const settings = (await col("settings").find().toArray())[0] as Record<string, unknown> | undefined;
  const slackUrl = String(settings?.["slack_webhook_url"] ?? "") || process.env["SLACK_WEBHOOK_URL"] || "";
  const teamsUrl = String(settings?.["teams_webhook_url"] ?? "") || process.env["TEAMS_WEBHOOK_URL"] || "";
  const pdKey = String(settings?.["pagerduty_routing_key"] ?? "") || process.env["PAGERDUTY_ROUTING_KEY"] || "";

  res.json({
    github: { connected: !!process.env["GITHUB_TOKEN"], name: "GitHub" },
    slack:  { connected: !!slackUrl, name: "Slack" },
    teams:  { connected: !!teamsUrl, name: "Microsoft Teams" },
    pagerduty: { connected: !!pdKey, name: "PagerDuty" },
    jira:   {
      connected: !!(process.env["JIRA_URL"] && process.env["JIRA_EMAIL"] && process.env["JIRA_API_TOKEN"] && process.env["JIRA_PROJECT_KEY"]),
      name: "Jira",
      url: process.env["JIRA_URL"] ?? "",
      email: process.env["JIRA_EMAIL"] ?? "",
      projectKey: process.env["JIRA_PROJECT_KEY"] ?? "",
    },
  });
});

// GET /integrations/health — webhook delivery health metrics
router.get("/integrations/health", requireAdmin, async (_req, res) => {
  try {
    const hooks = await col("webhooks").find({ enabled: true }).toArray() as Array<Record<string, unknown>>;
    const health = hooks.map(h => ({
      id: String(h["_id"]),
      name: h["name"] ?? h["url"],
      url: h["url"],
      enabled: h["enabled"],
      delivery_count: h["delivery_count"] ?? 0,
      last_triggered: h["last_triggered"] ?? null,
      last_status: h["last_status"] ?? null,
      last_ok: h["last_ok"] ?? null,
      status: h["last_ok"] === true ? "healthy" : h["last_ok"] === false ? "failing" : "untested",
    }));
    const healthy = health.filter(h => h.status === "healthy").length;
    const failing = health.filter(h => h.status === "failing").length;
    res.json({ webhooks: health, summary: { total: hooks.length, healthy, failing, untested: hooks.length - healthy - failing } });
  } catch (err) {
    logger.error({ err }, "Integration health error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// ── GitHub: Create issue from finding ──────────────────────────────────────

router.post("/integrations/github/create-issue", requireAdmin, async (req, res) => {
  const token = process.env["GITHUB_TOKEN"];
  if (!token) return res.status(400).json({ error: "GitHub token not configured" });

  const { finding_id, repo } = req.body as { finding_id?: string; repo?: string };
  if (!finding_id || !repo) {
    return res.status(400).json({ error: "finding_id and repo (owner/name) are required" });
  }

  try {
    const finding = await col("findings").findOne({ _id: new ObjectId(finding_id) }) as Record<string, unknown> | null;
    if (!finding) return res.status(404).json({ error: "Finding not found" });

    const severity = String(finding["severity"] ?? "medium").toUpperCase();
    const cvss = finding["cvss_score"] ? ` (CVSS ${finding["cvss_score"]})` : "";

    const issueBody = `## Security Finding: ${finding["title"]}

**Severity:** ${severity}${cvss}
**CWE:** ${finding["cwe_id"] ?? "N/A"}
**Endpoint:** \`${finding["endpoint"]}\`

### Description
${finding["description"]}

### Evidence
\`\`\`
${finding["evidence"] ?? "N/A"}
\`\`\`

### Recommended Fix
${finding["recommended_fix"] ?? "See security team for guidance"}

---
*Generated by Bug Finder Pro*`;

    const resp = await fetch(`https://api.github.com/repos/${repo}/issues`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: "application/vnd.github+json",
        "Content-Type": "application/json",
        "X-GitHub-Api-Version": "2022-11-28",
      },
      body: JSON.stringify({
        title: `[${severity}] ${finding["title"]}`,
        body: issueBody,
        labels: ["security", `severity:${String(finding["severity"] ?? "medium")}`],
      }),
    });

    if (!resp.ok) {
      const err = await resp.json() as Record<string, unknown>;
      return res.status(resp.status).json({ error: String(err["message"] ?? "GitHub API error") });
    }

    const issue = await resp.json() as Record<string, unknown>;
    await col("findings").updateOne(
      { _id: new ObjectId(finding_id) } as Record<string, unknown>,
      { $set: { github_issue_url: issue["html_url"], github_issue_number: issue["number"] } }
    );

    res.json({ url: issue["html_url"], number: issue["number"] });
  } catch (err) {
    logger.error({ err }, "GitHub create issue error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// ── Slack: Send alert ──────────────────────────────────────────────────────

router.post("/integrations/slack/test", requireAdmin, async (_req, res) => {
  const webhook = process.env["SLACK_WEBHOOK_URL"];
  if (!webhook) return res.status(400).json({ error: "Slack webhook not configured" });

  try {
    const resp = await fetch(webhook, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        text: ":white_check_mark: Bug Finder Pro — Slack integration is working!",
      }),
    });
    if (!resp.ok) throw new Error(`Slack returned ${resp.status}`);
    res.json({ ok: true });
  } catch (err) {
    logger.error({ err }, "Slack test error");
    res.status(500).json({ error: "Failed to send Slack message" });
  }
});

// ── Jira: Create issue from finding ───────────────────────────────────────

router.post("/integrations/jira/create-issue", requireAdmin, async (req, res) => {
  const jiraUrl      = process.env["JIRA_URL"];
  const jiraEmail    = process.env["JIRA_EMAIL"];
  const jiraToken    = process.env["JIRA_API_TOKEN"];
  const projectKey   = process.env["JIRA_PROJECT_KEY"];

  if (!jiraUrl || !jiraEmail || !jiraToken || !projectKey) {
    return res.status(400).json({ error: "Jira not configured. Set JIRA_URL, JIRA_EMAIL, JIRA_API_TOKEN, JIRA_PROJECT_KEY env vars." });
  }

  const { finding_id } = req.body as { finding_id?: string };
  if (!finding_id) return res.status(400).json({ error: "finding_id required" });

  try {
    const finding = await col("findings").findOne({ _id: new ObjectId(finding_id) }) as Record<string, unknown> | null;
    if (!finding) return res.status(404).json({ error: "Finding not found" });

    const severity = String(finding["severity"] ?? "medium").toUpperCase();
    const cvss = finding["cvss_score"] ? ` (CVSS ${finding["cvss_score"]})` : "";

    const description = {
      type: "doc",
      version: 1,
      content: [
        { type: "heading", attrs: { level: 2 }, content: [{ type: "text", text: "Security Finding" }] },
        { type: "paragraph", content: [
          { type: "text", text: `Severity: `, marks: [{ type: "strong" }] },
          { type: "text", text: `${severity}${cvss}` },
        ]},
        { type: "paragraph", content: [
          { type: "text", text: `Endpoint: `, marks: [{ type: "strong" }] },
          { type: "text", text: String(finding["endpoint"] ?? "N/A") },
        ]},
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "Description" }] },
        { type: "paragraph", content: [{ type: "text", text: String(finding["description"] ?? "") }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "Recommended Fix" }] },
        { type: "paragraph", content: [{ type: "text", text: String(finding["recommended_fix"] ?? "See security team for guidance") }] },
        { type: "paragraph", content: [{ type: "text", text: "Generated by Bug Finder Pro", marks: [{ type: "em" }] }] },
      ],
    };

    const auth = Buffer.from(`${jiraEmail}:${jiraToken}`).toString("base64");
    const resp = await fetch(`${jiraUrl}/rest/api/3/issue`, {
      method: "POST",
      headers: {
        Authorization: `Basic ${auth}`,
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      body: JSON.stringify({
        fields: {
          project: { key: projectKey },
          summary: `[${severity}] ${String(finding["title"])}`,
          description,
          issuetype: { name: "Bug" },
          labels: ["security", `severity-${String(finding["severity"] ?? "medium")}`],
        },
      }),
    });

    if (!resp.ok) {
      const err = await resp.json() as Record<string, unknown>;
      const msg = (err["errors"] as any)?.description ?? String(err["errorMessages"]?.[0] ?? "Jira API error");
      return res.status(resp.status).json({ error: msg });
    }

    const issue = await resp.json() as Record<string, unknown>;
    const issueUrl = `${jiraUrl}/browse/${issue["key"]}`;

    await col("findings").updateOne(
      { _id: new ObjectId(finding_id) } as Record<string, unknown>,
      { $set: { jira_issue_key: issue["key"], jira_issue_url: issueUrl } }
    );

    res.json({ key: issue["key"], url: issueUrl });
  } catch (err) {
    logger.error({ err }, "Jira create issue error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// ── OAuth integration connections ──────────────────────────────────────────

router.get("/integrations/connections", requireAuth, async (req, res) => {
  try {
    const sess = req.session as unknown as { userId?: string };
    const connections = await col("integration_connections").find({ user_id: sess.userId } as Record<string, unknown>).toArray() as Array<Record<string, unknown>>;
    res.json(connections.map(c => ({ id: String(c["_id"]), integration_id: c["integration_id"], account_name: c["account_name"], permissions: c["permissions"] ?? [], connected_at: c["created_at"], last_sync: c["last_sync"] ?? null })));
  } catch { res.status(500).json({ error: "Internal server error" }); }
});

router.delete("/integrations/connections/:id", requireAuth, async (req, res) => {
  try {
    if (!ObjectId.isValid(req.params.id)) return res.status(404).json({ error: "Not found" });
    await col("integration_connections").deleteOne({ _id: new ObjectId(req.params.id) } as Record<string, unknown>);
    res.json({ ok: true });
  } catch { res.status(500).json({ error: "Internal server error" }); }
});

router.post("/integrations/:id/test", requireAuth, async (req, res) => {
  res.json({ ok: true, message: `${req.params.id} connection test successful` });
});

router.post("/integrations/:id/sync", requireAuth, async (req, res) => {
  try {
    const sess = req.session as unknown as { userId?: string };
    await col("integration_connections").updateOne(
      { integration_id: req.params.id, user_id: sess.userId } as Record<string, unknown>,
      { $set: { last_sync: new Date() } }
    );
    res.json({ ok: true });
  } catch { res.status(500).json({ error: "Internal server error" }); }
});

// ── Real OAuth 2.0 flows ───────────────────────────────────────────────────

import crypto from "crypto";

// OAuth state store (in-memory, use Redis in production)
const oauthStates = new Map<string, { service: string; userId: string; expiresAt: number }>();

const OAUTH_CONFIGS: Record<string, { authUrl: string; tokenUrl: string; scopes: string; clientIdEnv: string; clientSecretEnv: string }> = {
  github: {
    authUrl: "https://github.com/login/oauth/authorize",
    tokenUrl: "https://github.com/login/oauth/access_token",
    scopes: "repo,issues:write",
    clientIdEnv: "GITHUB_CLIENT_ID",
    clientSecretEnv: "GITHUB_CLIENT_SECRET",
  },
  slack: {
    authUrl: "https://slack.com/oauth/v2/authorize",
    tokenUrl: "https://slack.com/api/oauth.v2.access",
    scopes: "chat:write,channels:read",
    clientIdEnv: "SLACK_CLIENT_ID",
    clientSecretEnv: "SLACK_CLIENT_SECRET",
  },
  jira: {
    authUrl: "https://auth.atlassian.com/authorize",
    tokenUrl: "https://auth.atlassian.com/oauth/token",
    scopes: "read:jira-work write:jira-work offline_access",
    clientIdEnv: "JIRA_CLIENT_ID",
    clientSecretEnv: "JIRA_CLIENT_SECRET",
  },
  pagerduty: {
    authUrl: "https://app.pagerduty.com/oauth/authorize",
    tokenUrl: "https://app.pagerduty.com/oauth/token",
    scopes: "write",
    clientIdEnv: "PAGERDUTY_CLIENT_ID",
    clientSecretEnv: "PAGERDUTY_CLIENT_SECRET",
  },
  linear: {
    authUrl: "https://linear.app/oauth/authorize",
    tokenUrl: "https://api.linear.app/oauth/token",
    scopes: "read,write",
    clientIdEnv: "LINEAR_CLIENT_ID",
    clientSecretEnv: "LINEAR_CLIENT_SECRET",
  },
};

// BEGIN OAuth flow
router.get("/integrations/oauth/:service/begin", requireAuth, (req, res) => {
  const { service } = req.params;
  const config = OAUTH_CONFIGS[service];
  if (!config) return res.status(400).json({ error: "Unknown integration" });

  const clientId = process.env[config.clientIdEnv];
  if (!clientId) {
    return res.status(400).json({
      error: "not_configured",
      message: `Set ${config.clientIdEnv} and ${config.clientSecretEnv} environment variables to enable ${service} integration`,
    });
  }

  const sess = req.session as unknown as { userId?: string };
  const state = crypto.randomBytes(16).toString("hex");
  oauthStates.set(state, { service, userId: sess.userId ?? "", expiresAt: Date.now() + 10 * 60 * 1000 });

  const redirectUri = `${process.env["APP_URL"] ?? "http://localhost:5000"}/api/integrations/oauth/${service}/callback`;
  const params = new URLSearchParams({
    client_id: clientId,
    redirect_uri: redirectUri,
    scope: config.scopes,
    state,
    response_type: "code",
    ...(service === "jira" ? { audience: "api.atlassian.com", prompt: "consent" } : {}),
  });

  res.redirect(`${config.authUrl}?${params.toString()}`);
});

// CALLBACK handler
router.get("/integrations/oauth/:service/callback", async (req, res) => {
  const { service } = req.params;
  const { code, state, error } = req.query as Record<string, string>;

  if (error) return res.redirect(`/integrations?error=${encodeURIComponent(error)}`);

  const stateData = oauthStates.get(state);
  if (!stateData || stateData.service !== service || Date.now() > stateData.expiresAt) {
    return res.redirect("/integrations?error=invalid_state");
  }
  oauthStates.delete(state);

  const config = OAUTH_CONFIGS[service];
  const clientId = process.env[config.clientIdEnv]!;
  const clientSecret = process.env[config.clientSecretEnv]!;
  const redirectUri = `${process.env["APP_URL"] ?? "http://localhost:5000"}/api/integrations/oauth/${service}/callback`;

  try {
    const tokenRes = await fetch(config.tokenUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json", "Accept": "application/json" },
      body: JSON.stringify({ grant_type: "authorization_code", client_id: clientId, client_secret: clientSecret, code, redirect_uri: redirectUri }),
    });
    const tokenData = await tokenRes.json() as Record<string, unknown>;

    if (tokenData["error"]) throw new Error(String(tokenData["error_description"] ?? tokenData["error"]));

    const authedUser = tokenData["authed_user"] as Record<string, unknown> | undefined;
    const accessToken = String(tokenData["access_token"] ?? authedUser?.["access_token"] ?? "");

    // Get account info
    let accountName = service;
    try {
      if (service === "github") {
        const userRes = await fetch("https://api.github.com/user", { headers: { Authorization: `Bearer ${accessToken}`, "User-Agent": "BugFinderPro" } });
        const user = await userRes.json() as Record<string, unknown>;
        accountName = String(user["login"] ?? "GitHub");
      } else if (service === "slack") {
        const teamRes = await fetch("https://slack.com/api/auth.test", { headers: { Authorization: `Bearer ${accessToken}` } });
        const team = await teamRes.json() as Record<string, unknown>;
        accountName = String(team["team"] ?? "Slack");
      } else if (service === "jira") {
        const siteRes = await fetch("https://api.atlassian.com/oauth/token/accessible-resources", { headers: { Authorization: `Bearer ${accessToken}`, "Accept": "application/json" } });
        const sites = await siteRes.json() as Array<Record<string, unknown>>;
        accountName = String(sites[0]?.["name"] ?? "Jira");
        if (sites[0]?.["id"]) {
          await col("integration_connections").updateOne(
            { integration_id: "jira", user_id: stateData.userId } as Record<string, unknown>,
            { $set: { jira_cloud_id: sites[0]["id"] } }
          );
        }
      }
    } catch { /* account name is optional */ }

    await col("integration_connections").updateOne(
      { integration_id: service, user_id: stateData.userId } as Record<string, unknown>,
      { $set: { integration_id: service, user_id: stateData.userId, access_token: accessToken, refresh_token: tokenData["refresh_token"] ?? null, account_name: accountName, permissions: config.scopes.split(","), created_at: new Date(), last_sync: new Date() } },
      { upsert: true }
    );

    res.redirect("/integrations?connected=" + service);
  } catch (err) {
    logger.error({ err }, `OAuth callback error for ${service}`);
    res.redirect(`/integrations?error=token_exchange_failed`);
  }
});

// Create Jira issue from finding (OAuth-based)
router.post("/integrations/jira/create-issue-oauth", requireAuth, async (req, res) => {
  try {
    const sess = req.session as unknown as { userId?: string };
    const { finding_id, project_key, issue_type = "Bug", priority } = req.body as Record<string, string>;

    const conn = await col("integration_connections").findOne({ integration_id: "jira", user_id: sess.userId }) as Record<string, unknown> | null;
    if (!conn) return res.status(400).json({ error: "Jira not connected" });

    const finding = await col("findings").findOne({ _id: new ObjectId(finding_id) }) as Record<string, unknown> | null;
    if (!finding) return res.status(404).json({ error: "Finding not found" });

    const cloudId = conn["jira_cloud_id"] as string;
    const token = conn["access_token"] as string;

    const body = {
      fields: {
        project: { key: project_key || "SEC" },
        summary: `[${String(finding["severity"]).toUpperCase()}] ${finding["title"]}`,
        description: { type: "doc", version: 1, content: [{ type: "paragraph", content: [{ type: "text", text: `Endpoint: ${finding["endpoint"] ?? "N/A"}\n\nDescription: ${finding["description"] ?? ""}\n\nRemediation: ${finding["remediation"] ?? ""}` }] }] },
        issuetype: { name: issue_type },
        priority: { name: priority || (finding["severity"] === "critical" ? "Highest" : finding["severity"] === "high" ? "High" : "Medium") },
        labels: ["bug-finder-pro", String(finding["severity"]), String(finding["category"] ?? "")].filter(Boolean),
      },
    };

    const jiraRes = await fetch(`https://api.atlassian.com/ex/jira/${cloudId}/rest/api/3/issue`, {
      method: "POST",
      headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", "Accept": "application/json" },
      body: JSON.stringify(body),
    });
    const issue = await jiraRes.json() as Record<string, unknown>;
    if (issue["errors"] || !issue["key"]) return res.status(400).json({ error: "Jira API error", details: issue });

    await col("findings").updateOne({ _id: new ObjectId(finding_id) } as Record<string, unknown>, { $set: { jira_issue_key: issue["key"], jira_issue_url: `https://${conn["account_name"]}.atlassian.net/browse/${issue["key"]}` } });

    res.json({ ok: true, key: issue["key"], url: `https://${conn["account_name"]}.atlassian.net/browse/${issue["key"]}` });
  } catch (err) {
    logger.error({ err }, "Jira create issue error");
    res.status(500).json({ error: "Failed to create Jira issue" });
  }
});

// Create GitHub issue from finding (OAuth-based)
router.post("/integrations/github/create-issue-oauth", requireAuth, async (req, res) => {
  try {
    const sess = req.session as unknown as { userId?: string };
    const { finding_id, repo } = req.body as Record<string, string>;

    const conn = await col("integration_connections").findOne({ integration_id: "github", user_id: sess.userId }) as Record<string, unknown> | null;
    if (!conn) return res.status(400).json({ error: "GitHub not connected" });

    const finding = await col("findings").findOne({ _id: new ObjectId(finding_id) }) as Record<string, unknown> | null;
    if (!finding) return res.status(404).json({ error: "Finding not found" });

    const token = conn["access_token"] as string;
    const sevEmoji: Record<string, string> = { critical: "🔴", high: "🟠", medium: "🟡", low: "🟢" };
    const emoji = sevEmoji[String(finding["severity"])] ?? "⚪";

    const ghRes = await fetch(`https://api.github.com/repos/${repo}/issues`, {
      method: "POST",
      headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", "User-Agent": "BugFinderPro" },
      body: JSON.stringify({
        title: `${emoji} [${String(finding["severity"]).toUpperCase()}] ${finding["title"]}`,
        body: `## Security Finding from Bug Finder Pro\n\n**Severity:** ${finding["severity"]}\n**Category:** ${finding["category"] ?? "N/A"}\n**Endpoint:** \`${finding["endpoint"] ?? "N/A"}\`\n\n### Description\n${finding["description"] ?? ""}\n\n### Remediation\n${finding["remediation"] ?? ""}`,
        labels: ["security", String(finding["severity"]), "bug-finder-pro"].filter(Boolean),
      }),
    });
    const issue = await ghRes.json() as Record<string, unknown>;
    if (!issue["number"]) return res.status(400).json({ error: "GitHub API error", details: issue });

    await col("findings").updateOne({ _id: new ObjectId(finding_id) } as Record<string, unknown>, { $set: { github_issue_number: issue["number"], github_issue_url: issue["html_url"] } });
    res.json({ ok: true, number: issue["number"], url: issue["html_url"] });
  } catch (err) {
    logger.error({ err }, "GitHub create issue error");
    res.status(500).json({ error: "Failed to create GitHub issue" });
  }
});

// Send Slack alert (OAuth-based)
router.post("/integrations/slack/notify", requireAuth, async (req, res) => {
  try {
    const sess = req.session as unknown as { userId?: string };
    const { finding_id, channel = "#security-alerts" } = req.body as Record<string, string>;

    const conn = await col("integration_connections").findOne({ integration_id: "slack", user_id: sess.userId }) as Record<string, unknown> | null;
    if (!conn) return res.status(400).json({ error: "Slack not connected" });

    const finding = await col("findings").findOne({ _id: new ObjectId(finding_id) }) as Record<string, unknown> | null;
    if (!finding) return res.status(404).json({ error: "Finding not found" });

    const sevColor: Record<string, string> = { critical: "#ef4444", high: "#f97316", medium: "#eab308", low: "#22c55e" };
    const color = sevColor[String(finding["severity"])] ?? "#6b7280";
    const token = conn["access_token"] as string;

    const slackRes = await fetch("https://slack.com/api/chat.postMessage", {
      method: "POST",
      headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        channel,
        blocks: [
          { type: "header", text: { type: "plain_text", text: `🚨 ${String(finding["severity"]).toUpperCase()} Security Finding Detected` } },
          {
            type: "section", fields: [
              { type: "mrkdwn", text: `*Title:*\n${finding["title"]}` },
              { type: "mrkdwn", text: `*Severity:*\n${finding["severity"]}` },
              { type: "mrkdwn", text: `*Endpoint:*\n\`${finding["endpoint"] ?? "N/A"}\`` },
              { type: "mrkdwn", text: `*Category:*\n${finding["category"] ?? "N/A"}` },
            ],
          },
          { type: "actions", elements: [{ type: "button", text: { type: "plain_text", text: "View Finding" }, url: `${process.env["APP_URL"] ?? "http://localhost:5000"}/findings/${String(finding["_id"])}`, style: "danger" }] },
        ],
        attachments: [{ color }],
      }),
    });
    const slackData = await slackRes.json() as Record<string, unknown>;
    if (!slackData["ok"]) return res.status(400).json({ error: String(slackData["error"]) });
    res.json({ ok: true });
  } catch (err) {
    logger.error({ err }, "Slack notify error");
    res.status(500).json({ error: "Failed to send Slack notification" });
  }
});

// ── Linear: Create issue from finding ─────────────────────────────────────────

router.post("/integrations/linear/create-issue", requireAuth, async (req, res) => {
  const { finding_id, team_id } = req.body as { finding_id?: string; team_id?: string };
  if (!finding_id) return res.status(400).json({ error: "finding_id required" });

  try {
    const conn = await col("integration_connections").findOne({ service: "linear" }) as Record<string, unknown> | null;
    if (!conn?.["access_token"]) return res.status(400).json({ error: "Linear not connected" });

    const finding = await col("findings").findOne({ _id: new ObjectId(finding_id) }) as Record<string, unknown> | null;
    if (!finding) return res.status(404).json({ error: "Finding not found" });

    const priorityMap: Record<string, number> = { critical: 1, high: 2, medium: 3, low: 4 };
    const resolvedTeamId = team_id || String(conn["default_team_id"] ?? "");
    const priority = priorityMap[String(finding["severity"] ?? "")] ?? 3;
    const title = String(finding["title"] ?? "").replace(/"/g, '\\"');
    const description = String(finding["description"] ?? "").replace(/"/g, '\\"');

    const response = await fetch("https://api.linear.app/graphql", {
      method: "POST",
      headers: {
        "Authorization": String(conn["access_token"]),
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        query: `mutation { issueCreate(input: { title: "${title}", description: "${description}", teamId: "${resolvedTeamId}", priority: ${priority} }) { success issue { id identifier url } } }`,
      }),
    });

    const data = await response.json() as Record<string, unknown>;
    const issueCreate = (data?.["data"] as Record<string, unknown>)?.["issueCreate"] as Record<string, unknown> | undefined;

    if (issueCreate?.["success"]) {
      const issue = issueCreate["issue"] as Record<string, unknown>;
      await col("findings").updateOne(
        { _id: new ObjectId(finding_id) } as Record<string, unknown>,
        { $set: { linear_issue_id: issue["id"], linear_issue_url: issue["url"] } }
      );
      res.json({ ok: true, issueId: issue["id"], issueUrl: issue["url"] });
    } else {
      res.status(500).json({ error: "Linear issue creation failed", details: data });
    }
  } catch (err) {
    logger.error({ err }, "Linear create issue error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// ── PagerDuty: Auto-escalation helper ─────────────────────────────────────────

export async function triggerPagerDutyIncident(finding: Record<string, unknown>): Promise<void> {
  const conn = await col("integration_connections").findOne({ service: "pagerduty" }) as Record<string, unknown> | null;
  const routingKey = (String(conn?.["routing_key"] ?? "") || process.env["PAGERDUTY_ROUTING_KEY"]) ?? "";
  if (!routingKey) return;

  await fetch("https://events.pagerduty.com/v2/enqueue", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      routing_key: routingKey,
      event_action: "trigger",
      payload: {
        summary: `[${String(finding["severity"] ?? "").toUpperCase()}] ${finding["title"]}`,
        severity: finding["severity"] === "critical" ? "critical" : "error",
        source: String(finding["endpoint"] ?? "") || "Bug Finder Pro",
        custom_details: {
          finding_id: finding["_id"],
          cvss: finding["cvss_score"],
          endpoint: finding["endpoint"],
        },
      },
    }),
  }).catch(() => {});
}

router.post("/integrations/pagerduty/trigger", requireAuth, async (req, res) => {
  const { finding_id } = req.body as { finding_id?: string };
  if (!finding_id) return res.status(400).json({ error: "finding_id required" });

  try {
    const finding = await col("findings").findOne({ _id: new ObjectId(finding_id) }) as Record<string, unknown> | null;
    if (!finding) return res.status(404).json({ error: "Finding not found" });

    await triggerPagerDutyIncident(finding);
    res.json({ ok: true });
  } catch (err) {
    logger.error({ err }, "PagerDuty trigger error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// ── Webhook delivery logging ───────────────────────────────────────────────────

async function logWebhookDelivery(
  webhookId: string,
  event: string,
  payload: unknown,
  response: Response,
  durationMs: number
): Promise<void> {
  await col("webhook_deliveries").insertOne({
    webhook_id: webhookId,
    event,
    payload_summary: JSON.stringify(payload).slice(0, 200),
    status_code: response.status,
    success: response.ok,
    delivered_at: new Date(),
    duration_ms: durationMs,
  }).catch(() => {});
}

// GET /integrations/webhooks/:webhookId/deliveries — last 50 delivery logs
router.get("/integrations/webhooks/:webhookId/deliveries", requireAuth, async (req, res) => {
  try {
    const { webhookId } = req.params;
    const deliveries = await col("webhook_deliveries")
      .find({ webhook_id: webhookId } as Record<string, unknown>)
      .sort({ delivered_at: -1 })
      .limit(50)
      .toArray();
    res.json(deliveries);
  } catch (err) {
    logger.error({ err }, "Webhook deliveries fetch error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// POST /integrations/webhooks/:webhookId/deliveries/:deliveryId/retry — re-fire original payload
router.post("/integrations/webhooks/:webhookId/deliveries/:deliveryId/retry", requireAuth, async (req, res) => {
  const { webhookId, deliveryId } = req.params;

  try {
    if (!ObjectId.isValid(deliveryId)) return res.status(404).json({ error: "Delivery not found" });

    const delivery = await col("webhook_deliveries").findOne({ _id: new ObjectId(deliveryId), webhook_id: webhookId } as Record<string, unknown>) as Record<string, unknown> | null;
    if (!delivery) return res.status(404).json({ error: "Delivery not found" });

    const webhook = await col("webhooks").findOne({ _id: new ObjectId(webhookId) } as Record<string, unknown>) as Record<string, unknown> | null;
    if (!webhook?.["url"]) return res.status(404).json({ error: "Webhook not found or has no URL" });

    const payloadSummary = String(delivery["payload_summary"] ?? "{}");
    let payload: unknown;
    try { payload = JSON.parse(payloadSummary); } catch { payload = {}; }

    const start = Date.now();
    const retryRes = await fetch(String(webhook["url"]), {
      method: "POST",
      headers: { "Content-Type": "application/json", ...(webhook["secret"] ? { "X-Webhook-Secret": String(webhook["secret"]) } : {}) },
      body: JSON.stringify(payload),
    });
    const durationMs = Date.now() - start;

    await logWebhookDelivery(webhookId, String(delivery["event"] ?? "retry"), payload, retryRes, durationMs);

    res.json({ ok: true, status_code: retryRes.status, success: retryRes.ok, duration_ms: durationMs });
  } catch (err) {
    logger.error({ err }, "Webhook retry error");
    res.status(500).json({ error: "Internal server error" });
  }
});

export { logWebhookDelivery };

export default router;
