import { Router } from "express";
import { ObjectId } from "mongodb";
import { col } from "../lib/db";
import { logger } from "../lib/logger";
import { requireAuth, requireAdmin } from "../middlewares/rbac";

const router = Router();

router.get("/integrations", requireAdmin, (_req, res) => {
  res.json({
    github: { connected: !!process.env["GITHUB_TOKEN"], name: "GitHub" },
    slack:  { connected: !!process.env["SLACK_WEBHOOK_URL"], name: "Slack" },
    jira:   {
      connected: !!(process.env["JIRA_URL"] && process.env["JIRA_EMAIL"] && process.env["JIRA_API_TOKEN"] && process.env["JIRA_PROJECT_KEY"]),
      name: "Jira",
      url: process.env["JIRA_URL"] ?? "",
      email: process.env["JIRA_EMAIL"] ?? "",
      projectKey: process.env["JIRA_PROJECT_KEY"] ?? "",
    },
  });
});

// ── GitHub: Create issue from finding ──────────────────────────────────────

router.post("/integrations/github/create-issue", requireAdmin, async (req, res) => {
  const token = process.env["GITHUB_TOKEN"];
  if (!token) return res.status(400).json({ error: "GitHub token not configured" });

  const { finding_id, repo } = req.body as { finding_id?: string; repo?: string };
  if (!finding_id || !repo) {
    return res.status(400).json({ error: "finding_id and repo (owner/name) are required" });
  }

  try {
    const finding = await col("findings").findOne({ _id: new ObjectId(finding_id) }) as Record<string, unknown> | null;
    if (!finding) return res.status(404).json({ error: "Finding not found" });

    const severity = String(finding["severity"] ?? "medium").toUpperCase();
    const cvss = finding["cvss_score"] ? ` (CVSS ${finding["cvss_score"]})` : "";

    const issueBody = `## Security Finding: ${finding["title"]}

**Severity:** ${severity}${cvss}
**CWE:** ${finding["cwe_id"] ?? "N/A"}
**Endpoint:** \`${finding["endpoint"]}\`

### Description
${finding["description"]}

### Evidence
\`\`\`
${finding["evidence"] ?? "N/A"}
\`\`\`

### Recommended Fix
${finding["recommended_fix"] ?? "See security team for guidance"}

---
*Generated by Bug Finder Pro*`;

    const resp = await fetch(`https://api.github.com/repos/${repo}/issues`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: "application/vnd.github+json",
        "Content-Type": "application/json",
        "X-GitHub-Api-Version": "2022-11-28",
      },
      body: JSON.stringify({
        title: `[${severity}] ${finding["title"]}`,
        body: issueBody,
        labels: ["security", `severity:${String(finding["severity"] ?? "medium")}`],
      }),
    });

    if (!resp.ok) {
      const err = await resp.json() as Record<string, unknown>;
      return res.status(resp.status).json({ error: String(err["message"] ?? "GitHub API error") });
    }

    const issue = await resp.json() as Record<string, unknown>;
    await col("findings").updateOne(
      { _id: new ObjectId(finding_id) } as Record<string, unknown>,
      { $set: { github_issue_url: issue["html_url"], github_issue_number: issue["number"] } }
    );

    res.json({ url: issue["html_url"], number: issue["number"] });
  } catch (err) {
    logger.error({ err }, "GitHub create issue error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// ── Slack: Send alert ──────────────────────────────────────────────────────

router.post("/integrations/slack/test", requireAdmin, async (_req, res) => {
  const webhook = process.env["SLACK_WEBHOOK_URL"];
  if (!webhook) return res.status(400).json({ error: "Slack webhook not configured" });

  try {
    const resp = await fetch(webhook, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        text: ":white_check_mark: Bug Finder Pro — Slack integration is working!",
      }),
    });
    if (!resp.ok) throw new Error(`Slack returned ${resp.status}`);
    res.json({ ok: true });
  } catch (err) {
    logger.error({ err }, "Slack test error");
    res.status(500).json({ error: "Failed to send Slack message" });
  }
});

// ── Jira: Create issue from finding ───────────────────────────────────────

router.post("/integrations/jira/create-issue", requireAdmin, async (req, res) => {
  const jiraUrl      = process.env["JIRA_URL"];
  const jiraEmail    = process.env["JIRA_EMAIL"];
  const jiraToken    = process.env["JIRA_API_TOKEN"];
  const projectKey   = process.env["JIRA_PROJECT_KEY"];

  if (!jiraUrl || !jiraEmail || !jiraToken || !projectKey) {
    return res.status(400).json({ error: "Jira not configured. Set JIRA_URL, JIRA_EMAIL, JIRA_API_TOKEN, JIRA_PROJECT_KEY env vars." });
  }

  const { finding_id } = req.body as { finding_id?: string };
  if (!finding_id) return res.status(400).json({ error: "finding_id required" });

  try {
    const finding = await col("findings").findOne({ _id: new ObjectId(finding_id) }) as Record<string, unknown> | null;
    if (!finding) return res.status(404).json({ error: "Finding not found" });

    const severity = String(finding["severity"] ?? "medium").toUpperCase();
    const cvss = finding["cvss_score"] ? ` (CVSS ${finding["cvss_score"]})` : "";

    const description = {
      type: "doc",
      version: 1,
      content: [
        { type: "heading", attrs: { level: 2 }, content: [{ type: "text", text: "Security Finding" }] },
        { type: "paragraph", content: [
          { type: "text", text: `Severity: `, marks: [{ type: "strong" }] },
          { type: "text", text: `${severity}${cvss}` },
        ]},
        { type: "paragraph", content: [
          { type: "text", text: `Endpoint: `, marks: [{ type: "strong" }] },
          { type: "text", text: String(finding["endpoint"] ?? "N/A") },
        ]},
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "Description" }] },
        { type: "paragraph", content: [{ type: "text", text: String(finding["description"] ?? "") }] },
        { type: "heading", attrs: { level: 3 }, content: [{ type: "text", text: "Recommended Fix" }] },
        { type: "paragraph", content: [{ type: "text", text: String(finding["recommended_fix"] ?? "See security team for guidance") }] },
        { type: "paragraph", content: [{ type: "text", text: "Generated by Bug Finder Pro", marks: [{ type: "em" }] }] },
      ],
    };

    const auth = Buffer.from(`${jiraEmail}:${jiraToken}`).toString("base64");
    const resp = await fetch(`${jiraUrl}/rest/api/3/issue`, {
      method: "POST",
      headers: {
        Authorization: `Basic ${auth}`,
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      body: JSON.stringify({
        fields: {
          project: { key: projectKey },
          summary: `[${severity}] ${String(finding["title"])}`,
          description,
          issuetype: { name: "Bug" },
          labels: ["security", `severity-${String(finding["severity"] ?? "medium")}`],
        },
      }),
    });

    if (!resp.ok) {
      const err = await resp.json() as Record<string, unknown>;
      const msg = (err["errors"] as any)?.description ?? String(err["errorMessages"]?.[0] ?? "Jira API error");
      return res.status(resp.status).json({ error: msg });
    }

    const issue = await resp.json() as Record<string, unknown>;
    const issueUrl = `${jiraUrl}/browse/${issue["key"]}`;

    await col("findings").updateOne(
      { _id: new ObjectId(finding_id) } as Record<string, unknown>,
      { $set: { jira_issue_key: issue["key"], jira_issue_url: issueUrl } }
    );

    res.json({ key: issue["key"], url: issueUrl });
  } catch (err) {
    logger.error({ err }, "Jira create issue error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// ── Scheduled Scans ────────────────────────────────────────────────────────

router.get("/scheduled-scans", requireAuth, async (_req, res) => {
  try {
    const scans = await col("scheduled_scans").find({}).sort({ created_at: -1 }).toArray() as Array<Record<string, unknown>>;
    res.json(scans.map((s) => ({ ...s, id: String(s["_id"]) })));
  } catch (err) {
    logger.error({ err }, "List scheduled scans error");
    res.status(500).json({ error: "Internal server error" });
  }
});

router.post("/scheduled-scans", requireAuth, async (req, res) => {
  try {
    const { target_url, scan_profile, cron_expression, validation_enabled, fuzzing_enabled, bug_bounty_mode } = req.body as {
      target_url?: string; scan_profile?: string; cron_expression?: string;
      validation_enabled?: boolean; fuzzing_enabled?: boolean; bug_bounty_mode?: boolean;
    };

    if (!target_url || !scan_profile || !cron_expression) {
      return res.status(400).json({ error: "target_url, scan_profile, and cron_expression are required" });
    }

    const { scheduleJob } = await import("../services/scheduler");
    const insert = await col("scheduled_scans").insertOne({
      target_url, scan_profile, cron_expression, enabled: true,
      validation_enabled: validation_enabled ?? false,
      fuzzing_enabled: fuzzing_enabled ?? false,
      bug_bounty_mode: bug_bounty_mode ?? false,
      created_at: new Date(), updated_at: new Date(),
    });

    const saved = await col("scheduled_scans").findOne({ _id: insert.insertedId }) as Record<string, unknown>;
    scheduleJob(saved as Parameters<typeof scheduleJob>[0]);
    res.status(201).json({ ...saved, id: String(saved["_id"]) });
  } catch (err) {
    logger.error({ err }, "Create scheduled scan error");
    res.status(500).json({ error: "Internal server error" });
  }
});

router.delete("/scheduled-scans/:id", requireAuth, async (req, res) => {
  try {
    const { id } = req.params;
    const { unscheduleJob } = await import("../services/scheduler");
    unscheduleJob(id);
    await col("scheduled_scans").deleteOne({ _id: new ObjectId(id) } as Record<string, unknown>);
    res.json({ ok: true });
  } catch (err) {
    logger.error({ err }, "Delete scheduled scan error");
    res.status(500).json({ error: "Internal server error" });
  }
});

export default router;
