import { Router } from "express";
import rateLimit from "express-rate-limit";
import { ObjectId } from "mongodb";
import { col } from "../lib/db";
import { logger } from "../lib/logger";
import { sendEmail } from "../services/email";
import { requireAuth } from "../middlewares/rbac";

const router = Router();

const digestLimiter = rateLimit({
  windowMs: 60 * 60 * 1000,
  max: 5,
  message: { error: "Too many digest requests — try again later" },
});

router.post("/notifications/digest", requireAuth, digestLimiter, async (req, res) => {
  try {
    const { email: recipient } = req.body as { email?: string };
    if (!recipient) return res.status(400).json({ error: "email is required" });

    const [recentFindings, recentScans, activeRemediations] = await Promise.all([
      col("findings").find({}).sort({ created_at: -1 }).limit(10).toArray() as Promise<Array<Record<string, unknown>>>,
      col("scan_jobs").find({ status: "completed" }).sort({ completed_at: -1 }).limit(5).toArray() as Promise<Array<Record<string, unknown>>>,
      col("remediations").find({ status: { $in: ["pending", "in_progress"] } }).toArray() as Promise<Array<Record<string, unknown>>>,
    ]);

    const critCount = recentFindings.filter((f) => f["severity"] === "critical").length;
    const highCount = recentFindings.filter((f) => f["severity"] === "high").length;

    const subject = critCount > 0
      ? `⚠ Bug Finder — ${critCount} Critical Findings Need Attention`
      : highCount > 0
        ? `Bug Finder — ${highCount} High Findings Pending`
        : `Bug Finder — Weekly Security Digest`;

    const findingsList = recentFindings.slice(0, 5).map((f) =>
      `[${String(f["severity"]).toUpperCase()}] ${String(f["title"])} — ${String(f["endpoint"] ?? "")}`
    ).join("<br>");

    const html = `
      <h2>Bug Finder Pro — Security Digest</h2>
      <p><strong>Recent Scans:</strong> ${recentScans.length} completed</p>
      <p><strong>Active Remediations:</strong> ${activeRemediations.length} pending</p>
      <p><strong>Critical Findings:</strong> ${critCount} | <strong>High:</strong> ${highCount}</p>
      <hr>
      <h3>Recent Findings</h3>
      <p>${findingsList || "No recent findings."}</p>
      <hr>
      <p><small>Generated by Bug Finder Pro. Visit your dashboard for details.</small></p>
    `;

    try {
      await sendEmail({
        to: recipient,
        subject,
        html,
      });
      logger.info({ recipient }, "Digest email sent");
      res.json({ ok: true, message: `Digest sent to ${recipient}` });
    } catch (emailErr) {
      logger.warn({ err: emailErr }, "Email send failed (SMTP not configured?)");
      res.json({ ok: false, message: "Email sending not configured. Set SMTP_HOST env var.", html });
    }
  } catch (err) {
    logger.error({ err }, "Digest error");
    res.status(500).json({ error: "Digest generation failed" });
  }
});

// GET /notifications — list notifications for current user
router.get("/notifications", requireAuth, async (req, res) => {
  try {
    const session = (req as unknown as { session: Record<string, unknown> }).session;
    const userId = (session["userId"] as string) ?? null;
    const query: Record<string, unknown> = userId ? { $or: [{ user_id: userId }, { user_id: { $exists: false } }] } : {};
    const notifications = await col("notifications").find(query).sort({ created_at: -1 }).limit(100).toArray() as Array<Record<string, unknown>>;
    res.json(notifications.map((n) => ({
      id: String(n["_id"]),
      type: n["type"],
      title: n["title"],
      message: n["message"],
      read: n["read"] ?? false,
      created_at: n["created_at"],
      href: n["href"] ?? null,
      severity: n["severity"] ?? null,
    })));
  } catch (err) {
    logger.error({ err }, "List notifications error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// GET /notifications/unread-count — count of unread notifications
router.get("/notifications/unread-count", requireAuth, async (req, res) => {
  try {
    const session = (req as unknown as { session: Record<string, unknown> }).session;
    const userId = (session["userId"] as string) ?? null;
    const query: Record<string, unknown> = { read: { $ne: true } };
    if (userId) query["$or"] = [{ user_id: userId }, { user_id: { $exists: false } }];
    const count = await col("notifications").countDocuments(query);
    res.json({ count });
  } catch (err) {
    logger.error({ err }, "Unread count error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// POST /notifications/mark-all-read — mark all as read
router.post("/notifications/mark-all-read", requireAuth, async (req, res) => {
  try {
    const session = (req as unknown as { session: Record<string, unknown> }).session;
    const userId = (session["userId"] as string) ?? null;
    const query: Record<string, unknown> = { read: { $ne: true } };
    if (userId) query["$or"] = [{ user_id: userId }, { user_id: { $exists: false } }];
    await col("notifications").updateMany(query, { $set: { read: true, read_at: new Date() } });
    res.json({ ok: true });
  } catch (err) {
    logger.error({ err }, "Mark all read error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// DELETE /notifications/:id — delete a single notification
router.delete("/notifications/:id", requireAuth, async (req, res) => {
  try {
    const { id } = req.params;
    if (!ObjectId.isValid(id)) return res.status(404).json({ error: "Not found" });
    await col("notifications").deleteOne({ _id: new ObjectId(id) } as Record<string, unknown>);
    res.json({ ok: true });
  } catch (err) {
    logger.error({ err }, "Delete notification error");
    res.status(500).json({ error: "Internal server error" });
  }
});

export default router;
