import { Router } from "express";
import { col } from "../lib/db";
import { logger } from "../lib/logger";
import { sendEmail } from "../services/email";

const router = Router();

// POST /notifications/digest — Send a notification digest email
router.post("/notifications/digest", async (req, res) => {
  try {
    const { email: recipient } = req.body as { email?: string };
    if (!recipient) return res.status(400).json({ error: "email is required" });

    const [recentFindings, recentScans, activeRemediations] = await Promise.all([
      col("findings").find({}).sort({ created_at: -1 }).limit(10).toArray() as Promise<Array<Record<string, unknown>>>,
      col("scan_jobs").find({ status: "completed" }).sort({ completed_at: -1 }).limit(5).toArray() as Promise<Array<Record<string, unknown>>>,
      col("remediations").find({ status: { $in: ["pending", "in_progress"] } }).toArray() as Promise<Array<Record<string, unknown>>>,
    ]);

    const critCount = recentFindings.filter((f) => f["severity"] === "critical").length;
    const highCount = recentFindings.filter((f) => f["severity"] === "high").length;

    const subject = critCount > 0
      ? `⚠ Bug Finder — ${critCount} Critical Findings Need Attention`
      : highCount > 0
        ? `Bug Finder — ${highCount} High Findings Pending`
        : `Bug Finder — Weekly Security Digest`;

    const findingsList = recentFindings.slice(0, 5).map((f) =>
      `[${String(f["severity"]).toUpperCase()}] ${String(f["title"])} — ${String(f["endpoint"] ?? "")}`
    ).join("<br>");

    const html = `
      <h2>Bug Finder Pro — Security Digest</h2>
      <p><strong>Recent Scans:</strong> ${recentScans.length} completed</p>
      <p><strong>Active Remediations:</strong> ${activeRemediations.length} pending</p>
      <p><strong>Critical Findings:</strong> ${critCount} | <strong>High:</strong> ${highCount}</p>
      <hr>
      <h3>Recent Findings</h3>
      <p>${findingsList || "No recent findings."}</p>
      <hr>
      <p><small>Generated by Bug Finder Pro. Visit your dashboard for details.</small></p>
    `;

    try {
      await sendEmail({
        to: recipient,
        subject,
        html,
      });
      logger.info({ recipient }, "Digest email sent");
      res.json({ ok: true, message: `Digest sent to ${recipient}` });
    } catch (emailErr) {
      logger.warn({ err: emailErr }, "Email send failed (SMTP not configured?)");
      res.json({ ok: false, message: "Email sending not configured. Set SMTP_HOST env var.", html });
    }
  } catch (err) {
    logger.error({ err }, "Digest error");
    res.status(500).json({ error: "Digest generation failed" });
  }
});

export default router;
