import { Router } from "express";
import rateLimit from "express-rate-limit";
import { ObjectId } from "mongodb";
import { z } from "zod";
import { col } from "../lib/db";
import { logger } from "../lib/logger";
import { sendEmail } from "../services/email";
import { requireAuth } from "../middlewares/rbac";

const digestSchema = z.object({ email: z.string().email("Must be a valid email address") });
const prefSchema = z.object({
  channels: z.array(z.enum(["email", "slack", "teams", "pagerduty"])).optional(),
  notify_critical: z.boolean().optional(),
  notify_high: z.boolean().optional(),
  notify_scan_complete: z.boolean().optional(),
});

const router = Router();

const digestLimiter = rateLimit({
  windowMs: 60 * 60 * 1000,
  max: 5,
  message: { error: "Too many digest requests — try again later" },
});

router.post("/notifications/digest", requireAuth, digestLimiter, async (req, res) => {
  try {
    const parsed = digestSchema.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.errors[0]?.message ?? "Validation failed" });
    const { email: recipient } = parsed.data;

    const session = (req as unknown as { session: { userId?: string; role?: string } }).session;
    const userFilter = session?.role !== "admin" ? { user_id: session?.userId ?? null } : {};
    const [recentFindings, recentScans, activeRemediations] = await Promise.all([
      col("findings").find(userFilter).sort({ created_at: -1 }).limit(10).toArray() as Promise<Array<Record<string, unknown>>>,
      col("scan_jobs").find({ status: "completed", ...userFilter }).sort({ completed_at: -1 }).limit(5).toArray() as Promise<Array<Record<string, unknown>>>,
      col("remediations").find({ status: { $in: ["pending", "in_progress"] }, ...userFilter }).toArray() as Promise<Array<Record<string, unknown>>>,
    ]);

    const critCount = recentFindings.filter((f) => f["severity"] === "critical").length;
    const highCount = recentFindings.filter((f) => f["severity"] === "high").length;

    const subject = critCount > 0
      ? `⚠ Bug Finder — ${critCount} Critical Findings Need Attention`
      : highCount > 0
        ? `Bug Finder — ${highCount} High Findings Pending`
        : `Bug Finder — Weekly Security Digest`;

    const findingsList = recentFindings.slice(0, 5).map((f) =>
      `[${String(f["severity"]).toUpperCase()}] ${String(f["title"])} — ${String(f["endpoint"] ?? "")}`
    ).join("<br>");

    const html = `
      <h2>Bug Finder Pro — Security Digest</h2>
      <p><strong>Recent Scans:</strong> ${recentScans.length} completed</p>
      <p><strong>Active Remediations:</strong> ${activeRemediations.length} pending</p>
      <p><strong>Critical Findings:</strong> ${critCount} | <strong>High:</strong> ${highCount}</p>
      <hr>
      <h3>Recent Findings</h3>
      <p>${findingsList || "No recent findings."}</p>
      <hr>
      <p><small>Generated by Bug Finder Pro. Visit your dashboard for details.</small></p>
    `;

    try {
      await sendEmail({
        to: recipient,
        subject,
        html,
      });
      logger.info({ recipient }, "Digest email sent");
      res.json({ ok: true, message: `Digest sent to ${recipient}` });
    } catch (emailErr) {
      logger.warn({ err: emailErr }, "Email send failed (SMTP not configured?)");
      res.json({ ok: false, message: "Email sending not configured. Set SMTP_HOST env var.", html });
    }
  } catch (err) {
    logger.error({ err }, "Digest error");
    res.status(500).json({ error: "Digest generation failed" });
  }
});

// GET /notifications — list notifications for current user
router.get("/notifications", requireAuth, async (req, res) => {
  try {
    const session = (req as unknown as { session: Record<string, unknown> }).session;
    const userId = (session["userId"] as string) ?? null;
    const query: Record<string, unknown> = userId ? { $or: [{ user_id: userId }, { user_id: { $exists: false } }] } : {};
    const notifications = await col("notifications").find(query).sort({ created_at: -1 }).limit(100).toArray() as Array<Record<string, unknown>>;
    res.json(notifications.map((n) => ({
      id: String(n["_id"]),
      type: n["type"],
      title: n["title"],
      message: n["message"],
      read: n["read"] ?? false,
      created_at: n["created_at"],
      href: n["href"] ?? null,
      severity: n["severity"] ?? null,
    })));
  } catch (err) {
    logger.error({ err }, "List notifications error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// GET /notifications/unread-count — count of unread notifications
router.get("/notifications/unread-count", requireAuth, async (req, res) => {
  try {
    const session = (req as unknown as { session: Record<string, unknown> }).session;
    const userId = (session["userId"] as string) ?? null;
    const query: Record<string, unknown> = { read: { $ne: true } };
    if (userId) query["$or"] = [{ user_id: userId }, { user_id: { $exists: false } }];
    const count = await col("notifications").countDocuments(query);
    res.json({ count });
  } catch (err) {
    logger.error({ err }, "Unread count error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// POST /notifications/mark-all-read — mark all as read
router.post("/notifications/mark-all-read", requireAuth, async (req, res) => {
  try {
    const session = (req as unknown as { session: Record<string, unknown> }).session;
    const userId = (session["userId"] as string) ?? null;
    const query: Record<string, unknown> = { read: { $ne: true } };
    if (userId) query["$or"] = [{ user_id: userId }, { user_id: { $exists: false } }];
    await col("notifications").updateMany(query, { $set: { read: true, read_at: new Date() } });
    res.json({ ok: true });
  } catch (err) {
    logger.error({ err }, "Mark all read error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// PATCH /notifications/:id/read — mark a single notification as read
router.patch("/notifications/:id/read", requireAuth, async (req, res) => {
  try {
    const { id } = req.params;
    if (!ObjectId.isValid(id)) return res.status(404).json({ error: "Not found" });
    await col("notifications").updateOne(
      { _id: new ObjectId(id) } as Record<string, unknown>,
      { $set: { read: true, read_at: new Date() } }
    );
    res.json({ ok: true });
  } catch (err) {
    logger.error({ err }, "Mark read error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// POST /notifications/read-all — alias for mark-all-read (used by notification bell)
router.post("/notifications/read-all", requireAuth, async (req, res) => {
  try {
    const session = (req as unknown as { session: Record<string, unknown> }).session;
    const userId = (session["userId"] as string) ?? null;
    const query: Record<string, unknown> = { read: { $ne: true } };
    if (userId) query["$or"] = [{ user_id: userId }, { user_id: { $exists: false } }];
    await col("notifications").updateMany(query, { $set: { read: true, read_at: new Date() } });
    res.json({ ok: true });
  } catch (err) {
    logger.error({ err }, "Read-all error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// DELETE /notifications/:id — delete a single notification
router.delete("/notifications/:id", requireAuth, async (req, res) => {
  try {
    const { id } = req.params;
    if (!ObjectId.isValid(id)) return res.status(404).json({ error: "Not found" });
    await col("notifications").deleteOne({ _id: new ObjectId(id) } as Record<string, unknown>);
    res.json({ ok: true });
  } catch (err) {
    logger.error({ err }, "Delete notification error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// GET /notifications/preferences — get current user's notification preferences
router.get("/notifications/preferences", requireAuth, async (req, res) => {
  try {
    const session = (req as unknown as { session: Record<string, unknown> }).session;
    const userId = session["userId"] as string;
    const pref = await col("notification_preferences").findOne({ user_id: userId } as Record<string, unknown>) as Record<string, unknown> | null;
    res.json({
      channels: pref?.["channels"] ?? ["email"],
      notify_critical: pref?.["notify_critical"] ?? true,
      notify_high: pref?.["notify_high"] ?? true,
      notify_scan_complete: pref?.["notify_scan_complete"] ?? false,
    });
  } catch (err) {
    logger.error({ err }, "Get notification preferences error");
    res.status(500).json({ error: "Internal server error" });
  }
});

// PUT /notifications/preferences — update current user's notification preferences
router.put("/notifications/preferences", requireAuth, async (req, res) => {
  try {
    const parsed = prefSchema.safeParse(req.body);
    if (!parsed.success) return res.status(400).json({ error: parsed.error.errors[0]?.message ?? "Validation failed" });
    const session = (req as unknown as { session: Record<string, unknown> }).session;
    const userId = session["userId"] as string;
    await col("notification_preferences").updateOne(
      { user_id: userId } as Record<string, unknown>,
      { $set: { ...parsed.data, user_id: userId, updated_at: new Date() }, $setOnInsert: { created_at: new Date() } },
      { upsert: true }
    );
    res.json({ ok: true });
  } catch (err) {
    logger.error({ err }, "Update notification preferences error");
    res.status(500).json({ error: "Internal server error" });
  }
});

export default router;
